project:
  type: book
  output-dir: docs
book:
  title: "Investigaciones en gestión del riesgo de desastres para Colombia"
  author: "UNGRD"
  chapters:
    - index.qmd
    - 00_legal.qmd
    - part: "Investigaciones 2021"
      chapters:
        - art_evaluaci_n_probabilista_d.qmd

format:
  html:
    theme: [cosmo, theme.scss]
    toc: true
