---
title: "Nociones performativas del reasentamiento social por riesgo de desastre en Colombia: componentes psicosociales estratégicos para la sostenibilidad"
subtitle: "Investigaciones en gestión del riesgo de desastres para Colombia"
author: "UNGRD"
date: "2021"
title-block-banner: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=2072"
---

# **Nociones performativas del reasentamiento social por riesgo de desastre en Colombia: componentes psicosociales estratégicos para la sostenibilidad**  {#nociones-performativas-del-reasentamiento-social-por-riesgo-de-desastre-en-colombia:-componentes-psicosociales-estratégicos-para-la-sostenibilidad}


**William Oswaldo Gaviria Gutiérrez1\*, Viviana Ramírez Loaiza2 & Lina Andrea Zambrano Hernández3**

1Programa de Psicología y Observatorio Psicosocial para la Gestión del Riesgo de Desastres. Universidad de Manizales. Manizales, Colombia  
2Federación Luterana Mundial programa Colombia. Bogotá, Colombia  
3Programa de Psicología y Observatorio Psicosocial para la Gestión del Riesgo de Desastres. Universidad de Manizales. Manizales, Colombia

\*Autor de contacto: William Oswaldo Gaviria Gutiérrez. Programa de Psicología y Observatorio Psicosocial para la Gestión del Riesgo de Desastres. Universidad de Manizales. Manizales, Colombia. Correo-e: wgaviria@umanizales.edu.co

