---
title: "IDENTIFICACIÓN DEL AUTOR**"
subtitle: "Investigaciones en gestión del riesgo de desastres para Colombia"
author: "UNGRD"
date: "2021"
title-block-banner: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=2072"
---

# **IDENTIFICACIÓN DEL AUTOR**


Cesar Hidalgo 	[https://orcid.org/0000-0002-1796-8945](https://orcid.org/0000-0002-1796-8945)  
Johnny Vega		[https://orcid.org/0000-0002-0662-7213](https://orcid.org/0000-0002-0662-7213)

**BIBLIOGRAFÍA**

1. Jibson, R. W., Harp, E. L., & Michael, J. A. (1998). A method for producing digital probabilistic seismic landslide hazard maps. *Engineering Geology*, 58, 271-289. [https://doi.org/10.1016/S0013-7952(00)00039-9](https://doi.org/10.1016/S0013-7952\(00\)00039-9)

2. Jaiswal, P., & Van Westen, C. J. (2009). Estimating temporal probability for landslide initiation along transportation routes based on rainfall thresholds. *Geomorphology*, 112, 96-105. [https://doi.org/10.1016/j.geomorph.2009.05.008](https://doi.org/10.1016/j.geomorph.2009.05.008)

3. Jaiswal, P., Van Westen, C., & Jetten, V. (2010). Quantitative landslide hazard assessment along a transportation corridor in southern India. *Engineering Geology*, 116, 236-250. [https://doi.org/10.1016/j.enggeo.2010.09.005](https://doi.org/10.1016/j.enggeo.2010.09.005)

4. AMVA. (2009). *Amenaza, vulnerabilidad y riesgo por movimientos en masa, avenidas torrenciales e inundaciones en el Valle de Aburrá*. Formulación de propuestas de gestión. Medellín. 

5. Hidalgo, C. A., Vega, J. A., Assis, A. P., & Villarraga, M. R. (2012). Estimation of sliding threat in linear projects: roads in residual soils (Spanish). *Memorias del IV Simposio Panamericano de Deslizamientos*. Paipa: Sociedad Colombiana de Geotecnia. 

6. Hidalgo, C., & Vega, J. (2014). Estimación de la amenaza por deslizamientos detonados por sismos y lluvia (Valle de Aburrá-Colombia). *Revista EIA*, 11(22), 3-117. 

7. Zêrere, J., García, R., Oliveira, S., & Reis , E. (2008). Probabilistic landslide risk analysis considering direct costs in the area north of Lisbon (Portugal). *Geomorphology* (94), 467–495. [https://doi.org/10.1016/j.geomorph.2006.10.040](https://doi.org/10.1016/j.geomorph.2006.10.040)

8. Remondo, J., Bonachea, J., & Cendrero, A. (2008). Quantitative landslide risk assessment and mapping on the basis of recent occurrences. *Geomorphology*, 98(3-4), 496-507. [https://doi.org/10.1016/j.geomorph.2006.10.041](https://doi.org/10.1016/j.geomorph.2006.10.041)

9. Godt, J. W., Sener, B., Verdin, K. L., Wald, D. J., Harp, E. L., & Jibson, R. W. (2008). Rapid assessment earthquake-induced landsliding. *Proceedings of the First World Landslide Forum*, November, Parallel Sessions Volume, International Program on. Tokyo, Japan. 

10. Vega, J. A. (2013). *Estimación del riesgo por deslizamientos de laderas generados por eventos sísmicos en la ciudad de Medellín usando herramientas de la Geomática. Caso aplicado a edificaciones urbanas*. La Plata, Argentina: Facultad de Ingeniería y Ciencias Astronómicas y Geofísicas de la Universidad Nacional de La Plata.

11. Vega, J. A., & Hidalgo, C. A. (2017). Risk Assessment of Earthquake-Induced Landslides in Urban Zones. En M. Mikoš, B. Tiwari, Y. Yin & K. Sassa (Eds.), *Advancing Culture of Living with Landslide – Advances in Landslide Science,* (pp. 953-963), Volume 2\. Springer International Publishing. [https://doi:10.1007/978-3-319-53498-5](https://doi:10.1007/978-3-319-53498-5)

12. Dragicevic, S., Lai, T., & Balram, S. (2015). GIS-based multicriteria evaluation with multiscale analysis to characterize urban landslide susceptibility in data-scarce environments. *Habitat International*, 45, 114-125. [https://doi.org/10.1016/j.habitatint.2014.06.031](https://doi.org/10.1016/j.habitatint.2014.06.031)

13. Saboya, F., Alves, M., & Pinto, W. (2006). Assessment of failure susceptibility of soil slopes using fuzzy logic. *Engineering Geology*, 86, 211–224. [https://doi.org/10.1016/j.enggeo.2006.05.001](https://doi.org/10.1016/j.enggeo.2006.05.001)

14. Sepulveda, S. A., & Petley, D. N. (2015). Regional trends and controlling factors of fatal landslides in Latin America and the Caribbean. *Natural Hazards and Earth Systems Science*, 15, 1821–1833. [https://doi.org/10.5194/nhess-15-1821-2015](https://doi.org/10.5194/nhess-15-1821-2015)

15. Isaza-Restrepo, P. A., Martinez, H. E., & Hidalgo, C. A. (April de 2016). Methodology for quantitative landslide risk analysis in residential projects. Habitat International, 53, 403-412. https://doi.org/10.1016/j.habitatint.2015.12.012

16. Klose, M. (2015). *Landslide Databases as Tools for Integrated Assessment of Landslide Risk*. Switzerland: Springer, p. 156\. [https://doi.org/10.1007/978-3-319-20403-1](https://doi.org/10.1007/978-3-319-20403-1)

17. Bryant, E. A., Head, L., & Morrison, R. J. (2005). Planning for natural hazards-how can we mitigate the impacts. En R. J. Morrison, S. Quin, & E. A. Bryant (Eds.), *Proceedings of a symposium Planning for natural hazards-how can we mitigate the impacts,* (pp. 1-21). Wollongong: GeoQuEST Research Centre and School of Earth and Environmental Sciences, University of Wollongong.

18. Chowdhury, R., Flentje, P., & Bhattacharya, G. (2010). *Geotechnical Slope Analysis*. London, England: Taylor & Francis, p. 737\. [https://doi.org/10.1201/9780203864203-f](https://doi.org/10.1201/9780203864203-f)

19. Aristizabal, E., & Gomez, J. (2007). Inventario de emergências e desastres no vale de Aburrá originados por fenómenos naturais e antrópicos no período 1880-2007. *Revista Gestión y Ambiente,* 10(2), 17-30. 

20. Isaza, P. (2011). *Avaliação do Risco Aceitável por Escorregamentos de Encostas em Regiões Tropicais Montanhosas: Caso de Aplicação, Medellín \- Colômbia*. Dissertação de Mestrado. Brasilia: Departamento de Engenharia Civil, Universidade de Brasilia. 

21. Vélez, M., Hoyos, F., Vélez, J., & Gómez, S. (1993). A methodology for the study of the hydrogeologic parameters in landslides. *3a Conferencia Latinoamericana de Hidrogeología Urbana*, 349 – 359\. Cartagena. 

22. SGC. (2017). *Las amenazas por movimientos en masa de Colombia. Una visión a escala 1:100.000.* Bogotá: Servicio Geológico Colombiano, Bogotá: Servicio Geológico Colombiano, 2017, p. 319\.

23. SGC. (2015). *Guía metodológica para estudios de amenaza, vulnerabilidad y riesgo por movimientos en masa*. Bogotá: Servicio Geológico Colombiano, 2015, 179 p.

24. Hidalgo, C. A. (2013). *Incertezas, Vulnerabilidade e Avaliação de Risco Devido a Deslizamento em Estradas, Brasilia*. Tesis de doctorado Departamento de Engeniería Civil y Ambiental, Universidad de Brasilia, 2013, 250 p. 

25. DAPARD. (2015). *Plan Departamental para La Gestión del Riesgo de Desastres. Gobernación de Antioquia*. Medellín: Departamento Administrativo del Sistema de Prevención, Atención y Recuperación de Desastres en Antioquia.

26. GAIA. (2015). *Actualización de la Línea Base de Gestión del Riesgo y Mapa de Susceptibilidad al Cambio Climático 2014-2015 en la Jurisdicción de Corantioquia*. Corantioquia. Medellín: Corantioquia.

27. Vega, J. A., & Hidalgo, C. A. (2016). Quantitative risk assessment of landslides triggered by earthquakes and rainfall based on direct costs of urban buildings. *Geomorphology*, 273, 217–235. [https://doi.org/10.1016/j.geomorph.2016.07.032](https://doi.org/10.1016/j.geomorph.2016.07.032)

28. Ruiz-Vásquez, D., & Aristizábal, E. (2018). Landslide susceptibility assessment in mountainous and tropical scarce-data regions using remote sensing data: A case study in the Colombian Andes. *Geophysical Research Abstracts*, 20, EGU2018-3408

29. Fawcett, T. (2006). An introduction to ROC analysis. Pattern Recognition Letters, 27, 861–874. [https://doi:10.1016/j.patrec.2005.10.010](https://doi:10.1016/j.patrec.2005.10.010)

30. Pourghasemi, H. R., Jirandeh, A. G., Pradhan, B., Xu, C., Gokceoglu, C. (2013). Landslide susceptibility mapping using support vector machine and GIS at the Golestan Province, Iran. *Journal of Earth System Science*, 122, 2, 349–369. [https://doi:10.1007/s12040-013-0282-2](https://doi:10.1007/s12040-013-0282-2)

31. Dikshit, A., Satyam, N., Pradhan, B. (2019). Estimation of Rainfall‑Induced Landslides Using the TRIGRS Model. *Earth Systems and Environment*, 3, 575–584. [https://doi.org/10.1007/s41748-019-00125-w](https://doi.org/10.1007/s41748-019-00125-w)

32. Pradhan, A. M. S., Kim, Y. T. (2016). Evaluation of a combined spatial multi-criteria evaluation model and deterministic model for landslide susceptibility mapping. *Catena* 140, 125–139.  [https://doi.org/10.1016/j.catena.2016.01.022](%20https://doi.org/10.1016/j.catena.2016.01.022)

33. Kritikos, T., Davies, T. (2015). Assessment of rainfall-generated shallow landslide/debris-flow susceptibility and runout using a GIS-based approach: application to western Southern Alps of New Zealand. *Landslides*, 12, 1051–1075. [https://doi.org/10.1007/s10346-014-0533-6](https://doi.org/10.1007/s10346-014-0533-6)

34. Chen, W., Pourghasemib, H. R., Kornejadyc, A., Zhanga, N. (2017). Landslide spatial modeling: Introducing new ensembles of ANN, MaxEnt, and SVM machine learning techniques. *Geoderma*, 305, 314–327. [https://doi.org/10.1016/j.geoderma.2017.06.020](https://doi.org/10.1016/j.geoderma.2017.06.020)

35. Hidalgo, C.A., Vega, J.A., & Parra, M. (2017). Effect of the rainfall infiltration processes on the landslide hazard assessment of unsaturated soils in tropical mountainous regions. Engineering and Mathematical Topics in Rainfall, T. V. V. Hromadka II y P. Rao, Edits. Londres, Intechopen, pp. [https://doi.org/10.5772/intechopen.70821](https://doi.org/10.5772/intechopen.70821)

36. Safeland. (2011). D2.5: Physical vulnerability of elements at risk to landslides: Methodology for evaluation, fragility curves and damage states for buildings and lifelines. *SafeLand Living with landslide risk in Europe: Assessment, effects of global change, and risk management strategies*. 195 p.

37. Marin, A. L., Toro, L. J., & Uribe, S. I. (2008). Conectividad estructural del paisaje cafetero en la cuenca alta del rio San Juan, Suroeste Antioqueño, Colombia*. Boletín de Ciencias de la Tierra*, (23), 43-54.

11

