---
title: "BIBLIOGRAFÍA**"
subtitle: "Investigaciones en gestión del riesgo de desastres para Colombia"
author: "UNGRD"
date: "2021"
title-block-banner: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=2072"
---

# **BIBLIOGRAFÍA**


1. Correa, E., Sanahuja, H. y Ramírez, F. (2011). *Guía de Reasentamiento para poblaciones en riesgo de desastre.* Washington DC: Banco Mundial y GFDRR.

2. Correa, E (Comp.) (2011). *Reasentamiento preventivo de poblaciones en riesgo de desastre. Experiencias de América Latina*. Washington, D.C.: Banco Internacional de Reconstrucción y Fomento / Banco Mundial.

3. Chardon, A. & Suárez, J. (2010). Reasentar..., más allá de cuatro muros. Un análisis a partir de la teoría y la praxis del hábitat sostenible. *Revista Bitácora Urbano Territorial*, 1(16), 11-34.

4. Chardon A. (2010). Reasentamiento y poblaciones urbanas vulnerables en Colombia. Un análisis desde el hábitat, el desarrollo y la sostenibilidad en Manizales, Colombia. *Cuadernos de Investigación Urbanística,* (69), 50-70.

5. Robles, S. (2008). *Impactos del reasentamiento por vulnerabilidad en áreas de alto riesgo*. Bogotá, 1991-2005. Bogotá, D.C., Colombia: Universidad Nacional de Colombia.

6. Corporación Financiera Internacional. (2002). *Manual para la preparación de un plan de acción para el reasentamiento.* Washington, DC: Banco Mundial.

7. Jiménez, R. (2005) El censo en los planes de reasentamiento como instrumento metodológico para la aplicación de políticas sociales urbanas. *II Foro Técnico Regional sobre Reasentamiento de Población, Banco Mundial – Banco Interamericano de Desarrollo*. Bogotá D.C., mayo 25 al 27 de 2005\.

8. Holguín, G. (2011). *Caracterización del caso El Hatillo. Actores, dinámicas y conflictos*. Bogotá, D.C.: Pensamiento y Acción Social.

9. Vera, G. (2007). *Vulnerabilidad social y Desastres en el Totonacapan. Una historia persistente*. (Tesis doctoral). Iztapalapa, México: Universidad Autónoma Metropolitana.

10. Macías, J. (2008). *Reubicaciones por desastre. Análisis de intervención gubernamental comparada*. Tlalpan, México, D. F.: Fondo Sectorial.

11. Barrios, M. (2009). *Reubicación de comunidades por inundación y la vulnerabilidad social. El caso de Arroyo del Maíz, Poza Rica, Veracruz*. Tlalpan, México: Centro de Investigaciones y Estudios Superiores en Antropología Social.

12. Molina-Prieto, C. y Victoria, M. (2012). Diversidad social y reasentamiento de población, un reto más en la recuperación del río Bogotá. *Revista Nodo*, 7(13), 23-42.

13. Soledad, B.; Sigala, F.; Argueta, L.; Iglesias, V. (2015). Salud ambiental infantil en el contexto de la reubicación de familias de campamentos a viviendas sociales. *Revista Chilena de Pediatría*, 86(3), 152-160. https://doi.org/10.1016/j.rchipe.2015.06.001

14. Paulsen, A. y Cárdenas, C. (1998). *Reasentamiento poblacional forzoso originado en riesgos o desastres asociados con fenómenos naturales. Caso Armero y el volcán Arenas del Nevado del Ruiz*. Bogotá D.C.: Red de desarrollo sostenible de Colombia

15. Macías, J. (2001). *Reubicación de comunidades humanas. Entre la producción y la reducción de desastres*. México, D. F.: Universidad de Colima.

16. Peláez, L. (2013). *Realizaciones y sofismas del restablecimiento del hábitat en procesos de reasentamiento por alto riesgo: experiencias en Medellín: 1990-2010*. (Tesis de maestría). Medellín, Colombia: Universidad Nacional de Colombia.

17. Serje M. y S. Anzellini (comp.). (2011). *Los dilemas del reasentamiento. Debates y experiencias de la Mesa Nacional de Diálogos sobre Reasentamiento de Población*.  Universidad de los Andes, Bogotá: Ediciones Uniandes.

18. Echeverry, D., Prieto, J. y Vargas, H. (2011). Gerencia de proyectos y gestión del riesgo. En M. Serje y S. Anzellini (comp.), Los dilemas del reasentamiento. *Debates y experiencias de la Mesa Nacional de Diálogos sobre Reasentamiento de Población*. (pp. 45-55).  Universidad de los Andes, Bogotá: Ediciones Uniandes.

19. Caicedo, A. (2013). *Habitar Bajo Riesgo. Mapachico y Genoy. Zona de Amenaza Volcánica Alta (ZAVA) del volcán galeras. Municipio de Pasto. Nariño, Colombia*. (Tesis de maestría). Medellín: Universidad Nacional de Colombia.

20. Hurtado, J. y Chardon, A. (2012). *Vivienda social y reasentamiento, una visión crítica desde el hábitat*. Manizales, Colombia: Universidad Nacional de Colombia.

21. Serje, M. (2011). Los dilemas del reasentamiento. Introducción a los debates sobre procesos y proyectos d reasentamientos. En M. Serje y S. Anzellini (comp.), *Los dilemas del reasentamiento. Debates y experiencias de la Mesa Nacional de Diálogos sobre Reasentamiento de Población*. (pp. 14-42). Universidad de los Andes, Bogotá: Ediciones Uniandes.

22. Anzellini, S. (2011). El reasentamiento de Herrán como aprendizaje de gestión y diseño de proyectos. En M. Serje y S. Anzellini (comp.), *Los dilemas del reasentamiento. Debates y experiencias de la Mesa Nacional de Diálogos sobre Reasentamiento de Población*. (pp.  57-79). Universidad de los Andes, Bogotá: Ediciones Uniandes.

23. Gallart, A. y Greaves, P. (1992). Una experiencia de monitoreo del reasentamiento de población por la construcción de los proyectos hidroeléctricos Aguamilpa y Zimapán. *Alteridades*, 79-84.

24. Rey, C. (2010). Pobreza en un reasentamiento voluntario de población desplazada: caso Patio Grande. *Palobra*, (11), 58-82.  http://doi.org/d4g8

25. Ministerio de Transportes y Comunicaciones. (2005). *Marco conceptual de compensación y reasentamiento involuntario*. República de Perú.

26. Donis, J. (2010). *Evaluación Social “Marco de Políticas Reasentamiento” Proyecto de Fortalecimiento de Gobiernos Locales*. El Salvador: Sub-secretaría de Desarrollo Territorial y Descentralización.

27. Fondo de Adaptación. (2012). *Marco de Política de Reasentamiento Involuntario. Anexo VI*.  Argentina: Fondo de Adaptación: Aumento de la resiliencia climática y mejora del manejo sustentable de la tierra en el sudoeste de la provincia de Buenos Aires.

28. Villegas, J. (2005). *Honduras: hacia una política nacional de reasentamiento de población para la reducción del riesgo*. Borrador para discusión. Secretaría de Gobernación y Justicia: Honduras. 

29. Ministerio de Vivienda y Asentamientos Humanos. (2014). *Política Nacional de Vivienda y Asentamientos Humanos 2013 a 2030 y su plan de acción*. República de Costa Rica.

30. Sierra, A. (2009). La política de mitigación de los riesgos en las laderas de Quito: ¿qué vulnerabilidad combatir? *Bulletin de l'Institut français d'études andines*, 38(3), 737-753. https://doi.org/10.4000/bifea.2421

31. Alcaldía Mayor Bogotá D.C. (2005). *Marco de política y metodología de reasentamientos de población localizada en zonas de alto riesgo no mitigable, rondas de cuerpos de agua*. Bogotá D.C.: Caja Vivienda Popular.

32. Wilches-Chaux, G. (2009). *Nuevas miradas al territorio, la seguridad, la pobreza y la adaptación al cambio climático*. Colombia: Programa de las Naciones Unidas para el Desarrollo.

33. Ocampo, M. y Forero, P. (2013). *Desplazamiento forzado e itinerancias: mujeres reasentadas en la ciudad de Montería*. La búsqueda incansable de un territorio de vida. Tesis Psicológica, 8(1), 32-55.

34. Aronsson, L. (1992). Impresiones de un proyecto de reasentamiento. *Alteridades*, 2(4), 51- 59\.

35. García, A. (2010). *Plan de reasentamiento involuntario para las unidades sociales de la inspección de Boquerón* (Trabajo de grado). Girardot, Cundinamarca: Corporación Universitaria Minuto de Dios.

36. Hurtado, J. (2010) *Análisis físico-espacial de la vivienda de interés social en los procesos de reasentamiento poblacional desde la perspectiva del hábitat: de los asentamientos autogestionados vulnerables a las soluciones institucionales masivas de vivienda. Estudio de caso: barrio Altos de Santa Ana. Comuna Ciudadela del Norte, Manizales*. (Tesis 694 Maestría). Universidad Nacional de Colombia.

37. Mejía-Escalante, M. (2012). Habitabilidad en la vivienda social en edificios para población reasentada. El caso de Medellín, Colombia. *Revista Latinoamericana de Estudios Urbanos Regionales*, 38 (114), 203-227.  http://dx.doi.org/10.4067/S0250-12012000200008

38. Castro, B. (2009). *El reto de construir territorio*. (Trabajo de grado). Popayán, Colombia: Universidad del Cauca.

39. Olivera, A. y González, G. (2010). Enfoque multidimensional de la reconstrucción post-desastre de la vivienda social y el hábitat en países en vías de desarrollo: estudios de casos en Cuba. *Revista de la construcción*, 9(2), 53-62. https://doi.org/10.4067/S0-915X2010000200006

40. Bijit, K. (2012). El proceso de integración social de los refugiados palestinos reasentados en región de Valparaíso, Chile. *Revista de Estudios Transfronterizos*, 12(1), 155-180.  https://doi.org/10.4067/S0-09482012000100007

41. Mandujano, F., Rodríguez, J., Reyes, S. y Medina P. (2015). La erupción del volcán Chaitén: Voyerismo, desconfianza, academia y Estado. Consecuencias urbanas y sociales en la comunidad. *UNIVERSUM*, 30(2), 153-177.  https://doi.org/10.4067/S0-23762015000200010

42. Mena, E. (2011). Habitabilidad de la vivienda de interés social prioritaria en el marco de la   cultura. Reasentamiento de comunidades negras de Vallejuelos a Mirador de Calasanz en Medellín, Colombia. *Cuadernos de Vivienda y Urbanismo*, 4(8), 296-314.

43. Duque, J. (2006). El reasentamiento poblacional: fenómeno social, político y de progreso.  *Revista Estudios Socio-jurídicos*, 8(1), 145-165.

44. Quiñonez, M. (2011). La manera cultural: Entre el desarraigo y la territorialización. Una   experiencia de cartografía social en la zona de bajamar- Isla de Cascajal Buenaventura.  *Entramado*, 7(2), 156-171.

45. Mosquera, J. y Gómez, E. (2011). Bases Conceptuales para la Gestión Integral del Riesgo. *Luna Azul*, (34), 148-169.

46. Sandoval, V., Boano,C., González, C., y Albornoz, C. (2015). Explorando potenciales vínculos entre resiliencia y Justicia ambiental: el caso  de  Chaitén,  Chile.  *MAGALLANIA*, 43(3), 37-49. https://doi.org/10.4067/S0-22442015000300004

47. Wilches-Chaux, G. (1993). *La reubicación de San Cayetano*. Bogotá: Editorial carrera 7ª Ltda. http://dx.doi.org/10.4067/S0-22442015000300004 

48. Erazo, V. (2013). Contra discurso y divergencia. Juegos de lenguaje y relatos ilegítimos sobre el Volcán Galeras. *Tendencias*. 14(2), 120-142.

49. Balazote, A. (2002). Reasentamiento forzoso de población y regularización territorial en el Interfluvio Teuco-Bermejito (Provincia de Chaco). *Cuadernos de antropología Social*, (16), 165-184.  https://doi.org/10.34096/cas.i16.4608

50. Bartolomé, L. (2006). Reasentamientos forzados y el sistema de supervivencia de los pobres urbanos. *Avá. Revista de Antropología*, (8).

51. Hernández, J. (2000). *La comunidad indígena de Mosoco y el Terremoto de 1994*. En Partridge, W. *Reasentamiento en Colombia*. Bogotá, Colombia: Banco Mundial.

52. Partridge, W. (2000). *Reasentamiento en Colombia*. Bogotá, Colombia: Banco Mundial.

53. Departamento de Medio Ambiente y Desarrollo Social de la Corporación Financiera Internacional. (2002). *Manual para la preparación de un plan de acción para el reasentamiento*. Washington, D.C.: Corporación Financiera Internacional.

54. Alto Comisionado de las Naciones Unidas para los Refugiados. ACNUR. (2011). *Manual de Reasentamiento del ACNUR*. Ginebra. Suiza: ACNUR.  [https://doi.org/10.34096/cas.i16.4608](https://doi.org/10.34096/cas.i16.4608)

55. Wilches-Chaux, G. (2006). *Introducción al concepto de seguridad territorial*. Resumen del argumento central del libro “¿Qu-ENOS pasa?

56. Bonilla-Castro, E.y Rodríguez, P. (2005). *Más Allá del Dilema de los Métodos: La Investigación en Ciencias Sociales* (Tercera Edición). Bogotá, D.C.: Editorial Norma.

57. Gonzáles, E. (2013). Acerca del estado de la cuestión o sobre un pasado reciente en la investigación cualitativa con enfoque hermenéutico. *Uni-pluri/versidad*, 13(1), 60-63.

58. Gadamer, H. (2002). *Verdad y método II*. Salamanca: Ediciones Sígueme.

59. Hochman, E. y Montero M. (2005). *Investigación Documental. Técnicas y procedimientos*. Caracas: Panapo.

60. Botzen, W., Bouwer, L., Scussolini, P., Kuik, O., Haasnoot, M., Lawrence, J., Aerts, J. (2019). Integrated Disaster Risk Management and Adaptation. En R. Mechler, L. Bouwer, T. Schinko, S. Surminski & J. Linnerooth-Bayer (Eds.), *Loss and Damage from Climate Change. Climate Risk Management, Policy and Governance*. Springer, Cham. 

61. Bello, M. y Chaparro, R. (2010). *El daño desde el enfoque psicosocial. Iniciativas Universitarias para la paz y la convivencia*. Universidad Nacional de Colombia. Bogotá: Universidad Nacional.

62. Beristain, C. (2010). *Manual Sobre Perspectiva Psicosocial en la investigación de los Derechos Humanos*. Bilbao: Hegoa

63. Butler, J. (2002). *Cuerpos que importan. Sobre los límites materiales y discursivos del “sexo”*. Buenos Aires: Paidós.

64. Castro-Buitrago, E. y Vélez, J. (2018). Procesos de reasentamiento en Colombia: ¿una medida de adaptación y protección de derechos humanos de las víctimas del cambio climático? *Vniversitas*, (136), 1-23. https://doi.org/10.11144/Javeriana.vj136.prcm

65. Osorio, A. (2017). Urbanismo, reasentamiento de población y vivienda adecuada: desafíos para la defensa de los derechos humanos en los territorios. *Ratio Juris*, 12(24), 61-86. [https://doi.org/10.24142/raju.v12n24a3](https://doi.org/10.24142/raju.v12n24a3)

66. Ebel, Roland, & Kissmann, Susanne (2011). Desarrollo sostenible: la investigación en un contexto intercultural. *Ra Ximhai*, 7(1), 69-79. https://doi.org/10.35197/rx.07.01.2011.07.re

67. Ávila, Plinio Zarta. (2018). La sustentabilidad o sostenibilidad: un concepto poderoso para la humanidad. *Tabula Rasa*, (28), 409-423. [https://dx.doi.org/10.25058/20112742.n28.18](https://dx.doi.org/10.25058/20112742.n28.18)

68. Bermejo Gómez de Segura, R. (2014). *Del desarrollo sostenible según Brundtland a la sostenibilidad como biomimesis*. Universidad del País Vasco. 

**Otras referencias**

1. Comunicación personal 02\. Marzo de 2016\.

2. Comunicación Personal 01\. Febrero de 2016\.

3. Grupo Focal 01\. Marzo de 2016\.

4. Grupo Focal 05\. Abril de 2016\.

5. Grupo Focal 02\. Marzo de 2016\.

6. Grupo Focal 03\. Marzo de 2016).

7. Comunicación Personal 07\. Abril de 2016\.

**6**

