---
title: "IDENTIFICACIÓN DEL AUTOR**"
subtitle: "Investigaciones en gestión del riesgo de desastres para Colombia"
author: "UNGRD"
date: "2021"
title-block-banner: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=2072"
---

# **IDENTIFICACIÓN DEL AUTOR**


Rafael Fernández	[https://orcid.org/0000-0002-2585-1958](https://orcid.org/0000-0002-2585-1958)  
Luis Yamin		[https://orcid.org/0000-0002-6533-5480](https://orcid.org/0000-0002-6533-5480)  
Juan Carlos Reyes	[https://orcid.org/0000-0003-0690-2956](https://orcid.org/0000-0003-0690-2956)  
Angie García		[https://orcid.org/0000-0001-5701-3329](https://orcid.org/0000-0001-5701-3329)  
Gustavo Fuentes	[https://orcid.org/0000-0002-0916-1885](https://orcid.org/0000-0002-0916-1885)  
Juan Echeverry	[https://orcid.org/0000-0001-6537-6381](https://orcid.org/0000-0001-6537-6381)

**BIBLIOGRÁFIA**

1. ICC (International Code Council). (2017). *2018 International Building Code*. International Code Council, Incorporated.

2. EERI (Earthquake Engineering Research Institute). (2019). *Concrete Buildings Damaged in Earthquakes*. Recuperado de [https://j.mp/3jtiOpm](https://j.mp/3jtiOpm)

3. Chen, H., Xie, Q., Lan, R., Li, Z., Xu , C., & Yu, S. (2017). Seismic damage to schools subjected to Nepal earthquakes, 2015\. *Natural Hazards*, 88(1), 247–84. [https://doi.org/10.1007/s11069-017-2865-8](https://doi.org/10.1007/s11069-017-2865-8)

4. GEER. (2017). Geotechnical engineering reconnaissance of the 19 September 2017 mw 7.1 Puebla-Mexico City earthquake (September). *Geotechnical Extreme Events Reconnaissance Association*. [https://doi.org/10.18118/g6jd46](https://doi.org/10.18118/g6jd46)

5. GEER. (2016). GEER-ATC earthquake reconnaissance April 16th 2016, Muisne, Ecuador. *Geotechnical Extreme Events reconnaissance Association Report* GEER-049. 604\. Recuperado de [https://j.mp/3hprJ9k](https://j.mp/3hprJ9k)

6. Valcárcel, J.A., Mora, M.G., Cardona, O.D., Pujades, L.G., Barbat, A.H., & Bernal, G.A. (2013) Methodology and applications for the benefit cost analysis of the seismic risk reduction in building portfolios at broadscale. *Natural Hazards*, 69(1), 845–68. [https://doi.org/10.1007/s11069-013-0739-2](https://doi.org/10.1007/s11069-013-0739-2)

7. Mora. M.G., Valcárcel, J. A., Cardona, O.D., Pujades, L. G., Barbat, A. H., & Bernal, G. A. (2015) Prioritizing interventions to reduce seismic vulnerability in school facilities in Colombia. *Earthquake Spectra*, 31(4), 2535–52. [https://doi.org/10.1193/040412EQS151T](https://doi.org/10.1193/040412EQS151T)

8. Chrysostomou, C. Z., Kyriakides, N., Papanikolaou. V. K., Kappos, A. J., Dimitrakopoulos, E. G., & Giouvanidis, A. I. (2015). Vulnerability assessment and feasibility analysis of seismic strengthening of school buildings. *Bulletin of Earthquake Engineering*, 13, 3809–40.  [https://doi.org/10.1007/s10518-015-9791-5](https://doi.org/10.1007/s10518-015-9791-5)

9. Jaimes, M. A., & Niño, M. (2017) Cost-benefit analysis to assess seismic mitigation options in Mexican public-school buildings. *Bulletin of Earthquake Engineering*, 15(9), 3919–42. [https://doi.org/10.1007/s10518-017-0119-5](https://doi.org/10.1007/s10518-017-0119-5)

10. Samadian, D., Ghafory-Ashtiany, M., Naderpour, H., & Eghbali, M. (2019). Seismic resilience evaluation based on vulnerability curves for existing and retrofitted typical RC school buildings. *Soil Dynamics and Earthquake Engineering*, 127, 105844\. [https://doi.org/10.1016/j.soildyn.2019.105844](https://doi.org/10.1016/j.soildyn.2019.105844)

11. Amini Hosseini, K., & Izadkhah, Y.O. (2020). From “Earthquake and safety” school drills to “safe school-resilient communities”: A continuous attempt for promoting community-based disaster risk management in Iran. *International Journal of Disaster Risk Reduction*, 45,101512. [https://doi.org/10.1016/j.ijdrr.2020.101512](https://doi.org/10.1016/j.ijdrr.2020.101512)

12. World Bank, Universidad de los Andes, UCL. (2019). *Global Library of School Infrastructure \- Taxonomy Guide. Global Program for Safer Schools*. Recuperado de [https://gpss.worldbank.org/index.php/en/node/571](https://gpss.worldbank.org/index.php/en/node/571)

13. World Bank, Universidad de los Andes, UCL. (2019). *Global Library for School Infrastructure \- Fragility and Vulnerability Assessment Guide. Global Program for Safer Schools*. Recuperado de [https://gpss.worldbank.org/index.php/en/glosi/vulnerability](https://gpss.worldbank.org/index.php/en/glosi/vulnerability)

14. Yamin, L., Ghesquiere, F., Cardona, O., & Ordaz, M. (2013). *Modelación probabilista para la gestión del riesgo de desastre, El caso de Bogotá, Colombia*. Banco Mundial, Universidad de los Andes. 

15. Yang, T. Y. (2013). Assessing seismic risks for new and existing buildings using performance-based earthquake engineering (PBEE) methodology. *Handbook of Seismic Risk Analysis and Management of Civil Infrastructure Systems*, 307–33. [https://doi.org/10.1533/9780857098986.3.307](https://doi.org/10.1533/9780857098986.3.307)

16. Baker, J. W. (2013). *Introduction to Probabilistic Seismic Hazard Analysis*. White Paper version 201\. 

17. Yamin. L. E, Reyes, J. C, Rueda, R., Prada, E., Rincón, R., Herrera, C., et al. (2018). Practical seismic microzonation in complex geological environments. *Soil Dynamics and Earthquake Engineering*, 114, 480–94. [https://doi.org/10.1016/j.soildyn.2018.07.030](https://doi.org/10.1016/j.soildyn.2018.07.030)

18. AIS (Asociación Colombiana de Ingeniería Sísmica). (2010). *Norma de construcción Sismo Resistente \- NSR10*. 530–827. Bogotá: Asociación Colombiana de Ingeniería Sísmica

19. FEMA (Federal Emergency Management Agency). (2017). *Hazus: FEMA’s Methodology for Estimating Potential Losses from Disasters*. Recuperado de https://www.fema.gov/hazus-mh-user-technical-manuals

20. Yamin, L. E., Hurtado, A. I, Barbat, A.H., & Cardona, O.D. (2014). Seismic and wind vulnerability assessment for the GAR-13 global risk assessment. *International Journal of Disaster Risk Reduction*, 10(PB), 452–60. [https://doi.org/10.1016/j.ijdrr.2014.05.007](https://doi.org/10.1016/j.ijdrr.2014.05.007)

21. D’Ayala, D., Meslem, A., Vamvatsikos, D., Porter, K., Rossetto, T., Crowley, H., et al. (2013). Guidelines for Analytical Vulnerability Assessment \- Low/Mid-Rise. *Global Earthquake Model Technical Report.* [https://doi.org/10.13117/GEM.VULN-MOD.TR2014.12](https://doi.org/10.13117/GEM.VULN-MOD.TR2014.12)

22. Yamin, L.E., Hurtado, A., Rincon, R., Dorado, J. F., & Reyes, J. C. (2017) Probabilistic seismic vulnerability assessment of buildings in terms of economic losses. *Engineering Structures*, 138, 30 8–23. [https://doi.org/10.1016/j.engstruct.2017.02.013](https://doi.org/10.1016/j.engstruct.2017.02.013)

23. Aroquipa, H., Rincón, R., & Fernandez, R. (2017). Evaluación de alternativas de reforzamiento sísmico incremental para edificaciones escolares características en el Perú. En *VIII Congreso Nacional de Ingeniería Sísmica*. Barranquilla, Colombia. 

24. American Society of Civil Engineers, Structural Engineering Institute. (2013*). Seismic evaluation and retrofit of existing buildings* (41-13). 1275 p. 

25. FEMA (Federal Emergency Management Agency) & ATC (Applied Technology Council). (2012). *Reducing the risks of nonstructural earthquake damage – A practical guide.* FEMA. 885 p.

26. British Columbia University. (2017). *The Seismic Retrofit Guidelines SGR-3*. 

27. ATC (Applied Technology Council). (1998). *Repair of Earthquake Damaged Concrete and Masonry Wall buildings.* Washington, D.C.: U.S. Dept. of Homeland Security, Federal Emergency Management Agency.

28. Rincón, R., Yamin, L., & Becerra, A. (2017). Seismic Risk Assessment of Public Schools and Prioritization Strategy for Risk Mitigation. En *16th World Conference on Earthquake*. Santiago Chile.

29. Fernández, R. I., Rincón. R., & Yamin, L. E. (2019). Incertidumbre en el Beneficio Obtenido para Opciones de Reforzamiento Sísmico. En *IX Congreso Nacional de Ingeniería Sísmica*. Cali, Colombia. 

30. Mechler, R. (2016). Reviewing estimates of the economic efficiency of disaster risk management: opportunities and limitations of using risk-based cost–benefit analysis. *Natural Hazards*, 81(3), 2121–47. [https://doi.org/10.1007/s11069-016-2170-y](https://doi.org/10.1007/s11069-016-2170-y)

31. Guevara, L. T., & García, L. E. (2005). The captive- and short-column effects. *Earthquake Spectra*, 21(1), 141–60. [https://doi.org/10.1193/1.1856533](https://doi.org/10.1193/1.1856533)

32. Villar-Vega, M., Silva, V., Crowley, H., Yepes, C., Tarque, N., Acevedo, A. B., … María, H. S. (2017). Development of a Fragility Model for the Residential Building Stock in South America. *Earthquake Spectra*, 33(2), 581–604. [https://doi.org/10.1193/010716EQS005M](https://doi.org/10.1193/010716EQS005M)

33. Adhikari, R. K., D’Ayala, D., Ferreira, C. F., & Famirez, F. (2018). Structural classification system for load bearing masonry school buildings. En *16th European Conference on Earthquake Engineering*. 1–12. 

34. Fuentes, G. A., Garcia, A, Yamin, L. E, Reyes, J. C. (2019). Funciones de fragilidad para muros de mampostería confinada ante cargas fuera del plano. En *IX Congreso Nacional de Ingeniería Sísmica*. Cali, Colombia.  

35. World Bank, Universidad de los Andes, UCL. (2018). *Información Técnica para el Plan de Mitigación del Riesgo Sísmico de las Edificaciones Escolares en El Salvador*. Bogotá: Universidad de los Andes.

36. CIMOC & Universidad de los Andes. (2019). *GPSS Informe técnico Asistencia técnica para el diseño de una estrategia de intervención y un plan de inversión para la reducción de la vulnerabilidad sísmica de edificaciones educativas en el municipio de Cali Plan Piloto 2019*. Bogotá: Universidad de los Andes.

37. Yamin, L. E., Garcia, A., Fuentes, G. A., Lopez, C., & Velez, L. (2019). Seismic performance assessment of representative school buildings. En *IX Congreso Nacional de Ingeniería Sísmica*. 

38. AMVA & Universidad de los Andes. (2017). Aunar Esfuerzos para la Armonización de la Microzonificación Sísmica de los Municipios del Valle de Aburrá, al Reglamento NSR-10 e Inclusión de los Cinco Corregimientos del Municipio de Medellín. Convenio marco de asociación 168 de 2015, Área Metropolitana del Valle de Aburrá, Universidad de los Andes. 

39. AMVA & Universidad de los Andes. (2018). Aunar esfuerzos para el desarrollo de los estudios de riesgo sísmico del Valle de Aburrá, continuación del Sistema de Información Sísmico del Valle de Aburrá, y la elaboración y formación de la metodología para la evaluación de edificaciones después de un sismo. Bogotá: Convenio de asociación 1108 de 2016, Área Metropolitana del Valle de Aburrá, Universidad de los Andes. 

	

**3**

