---
title: "Página Legal"
number-sections: false
---

Iván Duque Márquez

## Presidente de la República

Eduardo José González Angulo

## Director, Unidad Nacional para la Gestión del Riesgo de Desastres

Gerardo Jaramillo Montenegro

## Subdirector General, Unidad Nacional para la Gestión del Riesgo de Desastres

Lina Dorado

**Subdirectora para el Conocimiento del Riesgo, Unidad Nacional para la Gestión del Riesgo de Desastres**

Comisión Nacional Asesora para la Investigación en Gestión del Riesgo de Desastres (CNAIGRD)

## Editores

> Lina Dorado, Unidad Nacional para la Gestión del Riesgo de Desastres (UNGRD)
> 
> Argiro Ramírez, Ministerio de Ciencia, Tecnología e Innovación (Minciencias)
> 
> Omar Joaquín Agudelo, Centro de Estudios para la Prevención de Desastres (CEPREVE)
> 
> Marta Calvache, Servicio Geológico Colombiano (SGC)
> 
> Fabio Andrés Bernal, Instituto de Hidrología, Meteorología y Estudios Ambientales (IDEAM)
> 
> Leonor Aydé Rodríguez, Instituto Geográfico Agustín Codazzi (IGAC)
> 
> Wilson Ramírez, Instituto de Investigación de Recursos Biológicos Alexander von Humboldt (IAvH)
> 
> Capitán de Corbeta Cesar Grisales, Dirección General Marítima (DIMAR)
> 
> Alexander Figueroa, Ministerio de Ambiente y Desarrollo Sostenible (MINAMBIENTE)
> 
> Carolina Queruz, Ministerio de Educación Nacional (MEN)
> 
> Juan Pablo Londoño, Universidad de la Salle, representante universidades privadas
> 
> Lina Ospina Ostios, Universidad del Valle, representante universidades públicas
> 
> Carlos García, Red de universitarios de América Latina y el Caribe para la gestión y la reducción de
> 
> riesgos de emergencias y desastres (REDULAC/CAPCOLOMBIA)
> 
> Cristian Jaimes, Instituto Distrital de Gestión de Riegos y Cambio Climático (IDIGER)

## Equipo técnico, Subdirección para el Conocimiento del Riesgo, UNGRD

Luisa Cadena, Subdirección para el Conocimiento del Riesgo

Doralba Restrepo M., Subdirección para el Conocimiento del Riesgo

Mauricio Romero Torres, Subdirección para el Conocimiento del Riesgo

## Coordinación editorial

Mauricio Romero Torres

## Revisión de estilo

Kelly Barbosa

## Diseño y diagramación

Oficina de Comunicaciones: Jonathan Reyes

Subdirección para el Conocimiento del Riesgo: Hugo Niño, Alejandro Herrera, Hugo Vanstralen y Diana Mancera

## Proceso de arbitraje

Revisión por pares doble ciega para cada capítulo

**ISBN obra digital**: 000000000000000

Impresión digital: Unidad Nacional para la Gestión del Riesgo de Desastres

Bogotá, Colombia

Todos los derechos reservados. Esta publicación no puede ser reproducida ni total ni parcialmente

o transmitida por un sistema de recuperación de información, en ninguna forma ni por ningún medio,

sin el permiso previo de la UNGRD.

Distribución gratuita – versión digital

## Citación sugerida

Comisión Nacional Asesora para la Investigación en Gestión del Riesgo de Desastres (CNAIGRD) (Eds.). 2021. *Investigaciones en gestión del riesgo de desastres para Colombia. Avances, perspectivas y casos de estudio*. Unidad Nacional para la Gestión del Riesgo de Desastres. Bogotá, Colombia. 384 p.

<table>
<tbody>
<tr class="odd">
<td><p>Investigaciones en gestión del riesgo de desastres para Colombia. Avances, perspectivas y casos de estudio / Comisión Nacional Asesora para la Investigación en Gestión del Riesgo de Desastres.– Bogotá: Unidad Nacional para la Gestión del Riesgo de Desastres, 2021.</p>
<p>384 p.; 21.6 × 27.9 cm.</p>
<p>ISBN obra digital: 0000000000000</p>
<p>1.Conocimiento del riesgo 2. Estudios de riesgos 3. Reducción del riesgo—vulnerabilidad</p>
<p>I. Comisión Nacional Asesora para la Investigación en Gestión del Riesgo de Desastres (Eds.) II. Unidad Nacional para la Gestión del Riesgo de Desastres</p>
<p>CDD 363.6 H433 Hecho el depósito legal</p></td>
</tr>
</tbody>
</table>
