---
title: "Prólogo"
number-sections: false
---


Los desastres no son naturales. Los desastres son consecuencias de las construcciones sociales que derivan de vulnerabilidades al encontrarse con las amenazas, cualquiera sea su origen. No hay nada natural en los impactos producidos por desastres y los eventos naturales y antrópicos generadores de situaciones de desastre se han hecho más evidentes en todas las regiones del mundo y sus efectos socioeconómicos y las pérdidas humanas siguen aumentando, provocando impactos negativos en las dinámicas del desarrollo y en sus habitantes crecientes interrogantes en torno a las políticas de participación, información, protección y seguridad ciudadanas.

La región de las Américas y en especial, América Latina en la cuenca del Pacífico, son áreas frecuentemente impactadas por estos diferentes eventos los cuales generan situaciones de desastre, ocasionando pérdida de vidas, gran número de lesionados, pérdida de viviendas e infraestructura, deterioro ambiental, problemas de salud pública y una importante afectación en los avances del desarrollo social y económico de los países afectados.

Por su ubicación geográfica y sus condiciones geológicas, orográficas, topográficas y climáticas, Colombia presenta un alto grado de exposición a amenazas de origen natural y socio natural como sismos, actividad volcánica, geológico-marinos, meteorológicos, hidrológicos, climáticos, biológicos, astrofísicos, que conforman una amplia historia de eventos catastróficos que han conmocionado a distintas regiones del país. Igualmente, las amenazas antrópicas, generadas por la intervención humana, también se convierten en causantes o amplificadores de tan importantes impactos.

El desastre de Armero, ciudad del Departamento del Tolima, situado en el sur-centro occidental del país, sucedido el 13 de noviembre de 1985 por la erupción del volcán Nevado del Ruíz y su consecuente lahar, es el desastre por evento natural de mayor impacto en la historia conocida del país: 23.000 muertos, una ciudad destruida, otras varias muy afectadas, pérdidas económicas, infraestructurales, ambientales y culturales de amplísima cuantía y un gran impacto nacional e internacional por las dimensiones de sus efectos. Este evento se convirtió en el detonante de una respuesta social, gubernamental, institucional, normativa, que llevó a un abordaje progresivo de toda la temática pasando del manejo de la emergencia y las acciones de respuesta hacia la prevención y reducción de los desastres.

Se inicia, entonces, un trayecto político y normativo que con la expedición de la Ley 46 de 1988 creó el Sistema Nacional para la Prevención y Atención de Desastres y, con el respeto y aplicación de esta normativa, pero también, con el aporte de instituciones gubernamentales, ONGs, universidades, organizaciones comunitarias y de respuesta, se empieza a asumir un análisis en torno a los distintos factores que podrían estar estructurando el desastre y a asumirlo como una materialización anticipable, prevenible, modificable.

Así, las distintas instituciones, comunidades, sectores y gobiernos, empezamos a adentrarnos progresivamente en el aporte al conocimiento en torno a la amenaza y la vulnerabilidad como componentes del desastre, a entender que la exposición a las distintas amenazas se volvía determinante, que los desastres tienen una relación directa con los problemas no resueltos por el desarrollo y, por tanto, a considerar el Riesgo no como un evento sino como un proceso.

Precisamente, como procesos emergentes, en los últimos años ha sido creciente el interés alrededor de la estrecha relación de la naturaleza y la gestión del riesgo de desastres, ya que el espectro de eventos amenazantes es muy amplio pues comprende la gestión ante eventos geológicos, hidrometeorológicos, ambientales, biológicos, astrofísicos y, los años más recientes han puesto en evidencia la necesidad de un nuevo enfoque asociado a la gestión del cambio climático, la cual pretende incidir en las decisiones públicas y privadas para avanzar en una senda de desarrollo resiliente al clima y bajo en carbono, que reduzca los riesgos del cambio climático y permita aprovechar las oportunidades que éste genera (L1931/2018.Art.16). Otro enfoque creciente está relacionado ya no sólo a la naturaleza amenazada, sino a considerar a la naturaleza como una herramienta útil para gestionar algunas de las problemáticas asociadas al riesgo, siendo sencillas, de fácil implementación, sistémicas, más costo efectivas y sostenibles que las medidas tradicionales. Dichas medidas son reconocidas como Soluciones basadas en la Naturaleza-SbN, que se entienden como las funciones de los ecosistemas para resolver los problemas ambientales, en lugar de depender solamente de soluciones convencionales (Adaptado de IUCN, 2017).

Los anteriores ejemplos nos ponen frente al salto cualitativo más importante, porque el conocimiento del Riesgo se convierte en un determinante fundamental para asumir el Riesgo como proceso, a entender que ese conocimiento puede ir desde lo real hasta lo posible, que el país puede y está obligado a producir conocimiento, a aportar desde sus especificidades, a explorar el amplio espectro de los diferentes saberes, a invertir en prevención y reducción de riesgos y al manejo de estos cuando se materialicen. Así, está el país con todos los atributos acumulados e innovadores para asumir las dinámicas del proceso de la Gestión del Riesgo y la sistematización de su manejo integral, desde la Previsión y la Prevención hasta la Recuperación posterior a Desastres. Su mejor estructuración la asume el país con la expedición de la Ley 1523 de 2012 por la cual se adopta la Política Nacional de Gestión del Riesgo de Desastres y se establece el Sistema Nacional de Gestión del Riesgo de Desastres.

Dentro de esa nueva estructura, se establecen los Comités Nacionales para la Gestión del Riesgo y, entre ellos, el Comité Nacional para el Conocimiento del Riesgo establecido para asesorar y planificar la implementación de dicho proceso. Entre sus varias funciones, está la del estímulo al desarrollo del conocimiento, el acceso, la producción y generación de nuevo conocimiento y su difusión, y el dinamizador de estas potencialidades y compromisos ha sido la creación mediante Resolución 795 de 2014 de la Comisión Nacional Asesora de Investigación en Gestión del Riesgo de Desastres – CNAIGRD.

Ese compromiso por las posibilidades y potencialidades del conocimiento es el que hoy ponemos en evidencia con el aporte del método científico en las diferentes investigaciones y estudio de caso, y que este libro acoge para mostrar los logros de investigadores de distintas instituciones académicas, gubernamentales, sectoriales, de asesoría y servicio como muestra de soluciones desde el conocimiento a necesidades sentidas y prioritarias para mejorar el bienestar, la calidad de vida, la seguridad ciudadana y la sustentabilidad del desarrollo de nuestros países y regiones. Esperamos que esta sea la primera de varias publicaciones que muestren al público los últimos avances científicos en materia de Gestión del Riesgo de Desastres.

## Omar Joaquín Agudelo Suárez MD, Espc, MSc

Desarrollo Sustentable-Prevención y Atención de Desastres

Profesor Titular, Departamento de Pediatría, Facultad de Medicina, U. Nacional de Colombia

## Wilson Ariel Ramírez Hernández Ph.D.

Coordinador Gestión Territorial de la Biodiversidad

Instituto de Investigación de Recursos Biológicos Alexander von Humboldt

## Contenido

> [**Actualización de los coeficientes sísmicos de diseño estructural para la Norma Colombiana de Construcción Sismo Resistente NSR-22 4**](#_heading=h.fibvn7jo4kvn)

Gabriel Bernal & Omar Darío Cardona

> [**Mitigación del riesgo sísmico de la infraestructura escolar 45**](#_heading=h.yqdhanu41zca)

Rafael Fernández, Luis Yamin, Juan Carlos Reyes, Angie Garcia, Gustavo Fuentes & Juan Echeverry

> [**Evaluación probabilista del riesgo por sequía en el sector agrícola de Colombia 91**](#_heading=h.5pd0li8dgdvd)

Omar Darío Cardona, Gabriel Bernal, María Alejandra Escovar

> [**Contribución de la geodesia espacial en la gestión del riesgo en Colombia. Casos de estudio 160**](#_heading=h.ige8jje1k6li)
> 
> Héctor Mora-Páez, Fredy Díaz Mila, Takeshi Sagiya, Leidy Giraldo Londoño & Yuli Corchuelo Cuervo
> 
> [**Nociones performativas del reasentamiento social por riesgo de desastre en Colombia: componentes psicosociales estratégicos para la sostenibilidad 200**](#_heading=h.dv71bu414fn0)

William Oswaldo Gaviria Gutiérrez, Viviana Ramírez Loaiza & Lina Andrea Zambrano Hernández

> [**Animales en la gestión del riesgo de los desastres 229**](#_heading=h.yweixs8ma357)
> 
> Diego Hernández Pulido, Nicolás Hernández Gallo, Leonardo Arias Bernal, Rodrigo Forero Carrillo & Gonzalo Jiménez Alonso
> 
> [**Iniciativas para la reducción del riesgo de desastres en el programa de Ingeniería Ambiental y Sanitaria de la Universidad de La Salle: un tema de responsabilidad social universitaria 255**](#_heading=h.sgkc44rm5p7k)

Víctor Leonardo López Jiménez

> [**Comunicación del riesgo: reflexiones y experiencias locales en el departamento del Valle del Cauca 279**](#_heading=h.5m6ei4el6j79)
> 
> Javier Thomas & Julio Rubio
> 
> [**La perspectiva histórica en la gestión del riesgo de desastres: aplicación en Santiago de Cali, Colombia 301**](#_heading=h.cvn2idj5fbe3)
> 
> Nathalie García-Millán, Jorge A. Vélez-Correa, Karen A. Sánchez-Estupiñán, Nisley Zúñiga Estacio, Yeli C. Castillo-González, Alba N. Castaño-Castaño, Jorge A. Diaz-Rentería & Elkin De J. Salcedo-Hurtado
> 
> [**Estudio de riesgo por movimientos en masa en cuencas hidrográficas abastecedoras en el suroeste antioqueño usando métodos probabilistas 339**](#_heading=h.ixp7nsexganm)

Cesar Augusto Hidalgo M. & Johnny Alexander Vega G.

> [**De la percepción de la amenaza a su cuantificación. Caso de estudio: desbordamiento del río Unete en Aguazul, Casanare, Colombia 377**](#_heading=h.uk5pcfwjh69v)

Rafael Muñoz Quintero, Daniela Jácome Hernández, Alejandro Franco Rojas & Alexander Padilla González

> [**Obras costeras y clima marítimo: casos del Caribe colombiano 413**](#_heading=h.lt3s6g4ruu6r)

Serguei Lonin & Julio Monroy

> [**Modelo de gestión y análisis del riesgo por erosión costera. Caso de estudio departamento de Córdoba 433**](#_heading=h.cmudrxuqzl19)

Oswaldo Coca-Domínguez, Constanza Ricaurte-Villota & David Fernando Morales Giraldo

> [**Gestión del riesgo por inundaciones: un metamodelo para el desarrollo de artefactos participativos. Caso de estudio en la ecorregión de La Mojana (Colombia) 473**](#_heading=h.h0ceme7bm8h8)

Paula Andrea Villegas González & Nelson Obregón Neira

