---
title: "LA COMUNICACIÓN DEL RIESGO: ALGUNAS REFLEXIONES"
number-sections: false
---


Hablar de comunicación del riesgo nos obliga inicialmente a referenciar los trabajos centrales de la teoría de la comunicación planteados por Carey \[1\], Anderson \[2\], Holmes \[3\] y Lunenburg \[4\], y luego aquellos que implican directamente la comunicación del riesgo (Luhmann \[5\], Beck \[6\], Gonzalo y Farré \[7\]; Thomas, Rubio y Muñoz \[8\]), como parte integral de la gestión del riesgo, pero vinculada necesariamente con la teoría de la comunicación. Pero ¿qué implican una y otra?

Podría afirmarse que la teoría de la comunicación estudia la capacidad que tienen algunos seres vivos de relacionarse con otros intercambiando información, para controlar tanto su entorno, como los factores que los afectan, aislándolos de posibles factores perturbadores, como el ruido, el cual regularmente siempre está presente en el proceso y puede afectar en forma parcial o total el contenido del mensaje originalmente enviado \[9\]. No obstante, son en realidad múltiples intereses los que definen la investigación en comunicación y que consecuentemente inciden en su corpus teórico; Katz et al. (citado en \[10\]) identifica cinco universidades que establecen importantes campos de investigación: “Chicago, donde sitúan la primera investigación en comunicación; Columbia, donde Lazarsfeld y otros desarrollaron estudios sobre los efectos persuasivos y de gratificación de los medios en el público; Frankfurt, donde surge la investigación crítica; Toronto, donde Innis y McLuhan desarrollaron la corriente del determinismo tecnológico; y Birmingham, donde aparecen los estudios culturales. También mencionan París, con su gran tradición de estudios semióticos del cine y la cultura, y la Universidad de Yale, donde Hovland dirigió un importante grupo de investigación sobre la persuasión de masas”. Más importante en este momento que las Escuelas y sus representantes, resultan los ámbitos de trabajo que dibujan, de forma significativa, algunos de los aspectos prioritarios de la teoría de la comunicación: lingüística y semiótica, sociología de la comunicación de masas, estudios críticos, determinismo tecnológico y cibernética y estudios socioculturales, entre los mencionados.

<table>
<tbody>
<tr class="odd">
<td><p><strong>Caja 1. La comunicación humana</strong></p>
<p>Gifreu [11] establece que la comunicación humana es un proceso histórico, simbólico e interactivo, por el cual la realidad social se produce, comparte, conserva, controla y transforma simultáneamente. Esta interpretación pone de relieve las condiciones, dinámica, contextual, procesal, social, histórica, cultural y de poder del acto comunicativo, más allá de la semiótica y la lingüística.</p></td>
</tr>
</tbody>
</table>

Carey \[1\] convencido de la posibilidad de converger los estudios culturales genéricos con la investigación en comunicación, rompe la barrera existente entre sociedad y comunicación y orienta el enfoque de los primeros al estudio más concreto de los medios; ya Burke \[12\] había seguido el papel que juegan los estímulos durante el proceso de comunicación, estudiando la incidencia de los símbolos culturales en la forma como las personas se identifican con un grupo social. Para estos pensadores, la comunicación de masas tiene un importante carácter reflexivo, ya que no se trata sólo de describir o informar, sino que ella en sí misma crea y transforma las realidades y los sujetos mismos. La comunicación es entonces algo más que una observación de acontecimientos es una transmisión de un mensaje o un acercamiento de la audiencia a los medios masivos que tiene como resultante dialéctica los vectores de poder, los intereses y los actores sociales que delinean momentos de la realidad.

Más adelante con el impacto generado en la sociedad por el desarrollo de los medios de comunicación masiva, Bateson y Ruesch \[13\] introdujeron el concepto de metacomunicación, o comunicación sobre la comunicación, como un estudio de la comunicación más allá de las ideas superficiales y la transmisión de un mensaje. Como se observa, existen diversas y complejas perspectivas sobre la comunicación, pero nos quedaremos con la definición de comunicación humana de Gifreu \[11\], que en extenso define el alcance de la teoría de la comunicación que queremos relievar acá: “la comunicación humana es un proceso histórico, simbólico e interactivo por el cual la realidad social es producida, compartida, conservada, controlada y transformada”*.*

Esta definición hace evidente que, primero, el acto comunicativo es dinámico, contextual y procesal; segundo, es un hecho concreto en un espacio-tiempo particular; tercero, es producto de relaciones sociales entre sujetos, pero también produce relaciones sociales; agencia una sociedad que define símbolos, códigos que configuran imágenes, unas abstractas otras concretas; cuarto, que es un instrumento de poder que incide en su equilibrio y en las formas particulares que este adquiere en la sociedad.

Estos elementos mencionados son importantes, porque definen aspectos claves en la teoría de la comunicación que están presentes también, en mayor o menor medida, en la teoría de la comunicación del riesgo, a ver.

Iniciaremos preguntándonos ¿existe una teoría de la comunicación del riesgo o simplemente se trata de informar a la comunidad sobre los riesgos a los que está expuesta? ¿Materializa esta comunicación del riesgo relaciones de poder, asimetría de la información, percepciones sociales y/o institucionales y valoraciones y cálculos políticos o empresariales?

Basados en los argumentos expuestos anteriormente, es claro que comunicar no es lo mismo que informar. Informar trata de un proceso unidireccional, unilateral, que asume al receptor de un mensaje como sujeto pasivo, cuasi-objeto, que bajo un mecanismo causa-efecto, dispara una reacción en función del mensaje recibido; mientras que el comunicar implica una construcción conjunta de mensajes, en doble vía, en donde las interacciones permanentes entre emisor-receptor, generan constantes intercambios de sus roles y una reconfiguración continua de los mensajes. Es por tanto un proceso recíproco e iterativo de significación y resignificación de códigos y de construcción, deconstrucción y reconstrucción de significados, en aras de edificar socialmente lenguajes. Podríamos afirmar en consecuencia, que “la comunicación del riesgo se trata de un complejo proceso de reconocimiento, visibilización y configuración, de conceptos, intenciones, percepciones, reglas e incluso situaciones, en las que se construye pensamiento y acción sobre el riesgo y sus componentes y el significado e impacto social y político que adquiere su descodificación” \[8\].

En esta comunicación del riesgo juegan papel preponderante las particularidades del mundo contemporáneo que, como expresión de la sistemática, generalizada y vigorosa aplicación de la tecnología en todos y cada uno de los campos de la vida cotidiana, definen, como su impronta indeleble, una condición global del riesgo \[6\], \[5\], que debe ser visibilizada, reconocida y significada, para establecer, en lo posible, agentes, canales, implicaciones, responsables y alternativas posibles. No desde una perspectiva perturbadora o paranoica, sino desde aquella que permita acercarse a una dimensión social, política y ética del riesgo, que propicie una relación más equitativa, justa y diáfana con los actores hegemónicos y con las relaciones de poder que ellos despliegan y que subyacen a la construcción de vulnerabilidades y riesgos en sus diversas escalas y que, la mayoría de las veces, la comunicación masiva enmascara, desvirtúa o niega, al tiempo que los amplifica.

<table>
<tbody>
<tr class="odd">
<td><p><strong>Caja 2. La comunicación del riesgo</strong></p>
<p>La comunicación es un proceso recíproco e iterativo de significación y resignificación de códigos y de construcción, deconstrucción y reconstrucción de significados en aras de edificar socialmente lenguajes.</p>
<p>Por su parte, la comunicación del riesgo es un complejo proceso de identificación, significación, configuración, decodificación y asimilación social de conceptos, voluntades, valoraciones, reglas y condiciones, en las cuáles se construye pensamiento y acción sobre el riesgo y sus componentes y el significado e impacto social y político de éste.</p></td>
</tr>
</tbody>
</table>

“La ignorancia de la globalización del riesgo no hace más que incrementarlo” \[7\], ya que se reduce la percepción de éste, se diluyen las responsabilidades políticas e institucionales frente a él, se disipa la consciencia colectiva del riesgo, se desconocen o menguan las capacidades inherentes de la población, para responder efectivamente ante situaciones de riesgo y de emergencias, y se acallan o moderan las demandas sociales por justicia social, espacial y ambiental, como requisito *sine-quanon* para la reducción de las vulnerabilidades. No obstante, es importante tener presente, simultáneamente, las expresiones de aquello que Beck \[14\] llamó la Modernidad Reflexiva, o Giddens & Pierson \[15\] la incertidumbre fabricada, refiriéndose, en uno y otro caso, a las “consecuencias no deseadas de la modernidad” \[14\], y que materializan la permanente contradicción-dualidad entre conocimiento y riesgo. Es decir, a medida que crece el conocimiento, el riesgo lo hace de la mano de él, como respuesta a las nuevas condiciones, situaciones e información que se crean, fabricándose así sistémicos y complejos impactos, no imaginados o reconocidos por registros históricos, ya que no existen los datos previos que permitan modelar el comportamiento de éstos. Beck \[14\] asume la incertidumbre fabricada, como una “mezcla de riesgo, más conocimiento, más desconocimiento y reflexividad, y por tanto un nuevo tipo de riesgo”.

Es por esto que “la comunicación del riesgo más que herramienta al servicio de la información del Establecimiento debe permitir construir espacios, mecanismos e instrumentos permanentes de interacción y retroalimentación, tanto, entre los distintos niveles de la realidad que establece la sociedad del riesgo, como de la gestión social de éste y por ello, no puede considerarse ni independiente, ni externa, ni únicamente producto final, de salida, del proceso instrumental de la gestión del riesgo. Ésta debe contemplar las esferas políticas, técnica y social, como fuentes poderosas en los procesos de definición, significación y gestión del riesgo” \[8\].

Si “el riesgo es un juego de poder que en la era global cuenta con los gobiernos occidentales y el poder económico entre sus actores protagonistas” \[7\], entonces la comunicación del riesgo debe:

> “fortalecer la relación entre episteme, percepción, consciencia, ética (deontología) y gestión del riesgo, para producir procesos comunicativos que propicien la construcción de supuestos y acciones más acordes con condiciones de mayor seguridad de los individuos y las sociedades; en esa medida, es claro que la comunicación es un instrumento de poder al servicio de quien la maneja, si sus expresiones, relaciones e intenciones se hacen más transparentes, se resquebrajará la hegemonía y el poder de quien la controla y emergerán mayores demandas sociales de equidad a la información, de acceso a los recursos satisfactores, como condición de fortaleza ante amenazas y riesgos, y de responsabilidad política y empresarial ante los agentes y factores generadores de vulnerabilidad”\[8\].

La relación comunicación-conocimiento-consciencia-ética-gestión del riesgo, que es afectada por la percepción del riesgo y los sesgos asociados que ello implica, Sandman \[16\], correlaciona el nivel de molestia del público y el conocimiento-percepción de la amenaza de los expertos. Si aceptamos el modelo propuesto por él, se puede decir que la comunicación del riesgo pretende, en estos casos, equilibrar estas variables para generar respuestas propicias en el público que faciliten la gestión del riesgo.

Es claro aquí que sentimientos o sensaciones como temor, daño potencial, daño perceptible, controlabilidad de situaciones, incluidos en el concepto genérico de riesgo, se internalizan a través de la praxis cultural y social e inciden en la valoración perceptual de los riesgos, calificándolos como insignificantes, serios o inaceptables. Renn \[17\] y Rohrmann \[18\], mostraron datos empíricos sobre ello, en estudios realizados en Estados Unidos, Canadá, Alemania, Francia, Austria, Japón y Australia. De hecho, lo que la gente cree que es cierto acerca de un riesgo, pasa por la evaluación, consciente o intuitiva, de ese conocimiento y por el tamizaje de los referentes perceptuales y afectivos previos. Rohrmann \[18\] y Sjöberg \[19\] demostraron que los sentimientos emocionales acerca de los generadores de riesgo influyen en las evaluaciones de riesgo e inciden en la importancia asignada al daño potencial a sufrir. Así mismo, trabajos sobre la percepción de los riesgos tecnológicos \[Kals \[20\]\], también muestran que los factores emocionales y cognitivos se relacionan mutuamente, no obstante, persiste la duda sobre su relación causal; si las creencias cognitivas activan las respuestas emocionales respectivas, o, si los iniciales impulsos emocionales "construyen" argumentos que apoyen la postura emocional del individuo.

Lo cierto es que tanto los elementos cognitivos como los afectivos influyen en la percepción del riesgo y requieren ser reconocidos y abordados al comunicarse con el público en general o con grupos específicos. La comunicación del riesgo no puede ser efectiva sin una comprensión integral de cómo perciben, sienten, ponderan y evalúan los riesgos los individuos, y cuáles son los factores que determinan la variación de la percepción del riesgo, sujeto a sujeto, comunidad por comunidad.

Además, el marco social y político en el que individuo y grupos están insertos es esencial también, ya que inciden en el nivel de confianza que las instituciones generan, los valores y compromisos sociales que propician y asumen, la complejidad de sus estructuras, las limitaciones organizativas propias y el estatus socioeconómico que le posibilitan o crean a cada individuo. Una variable importante en la evaluación del riesgo es la percepción de equidad y justicia en la asignación de beneficios y riesgos a diferentes individuos y grupos sociales \[20,21\].

Las variables sociopolíticas, sin duda alguna juegan un papel importante en la configuración de las respuestas individuales y sociales al riesgo "público", y en la construcción de los debates sobre el riesgo. Tanto Luhmann \[22\], Giddens \[23\], como Beck \[6\], mostraron que en un entorno social en el que la experiencia personal se construye en gran medida a partir de información de segunda mano, la confianza es un requisito previo esencial para la comunicación y la coordinación social; confianza que puede ser fácilmente destruida por desastres no previsibles o abusada, fácilmente, relacionando los eventos al azar como explicaciones o excusas para los errores, negligencias o excesos cometidos en la gestión del riesgo. Por esto la confianza está constantemente en juego en las respuestas institucionales al riesgo. Cabe tener presente que “la ambigüedad en la asignación de causalidad o culpa a diversos actores (incluyendo la naturaleza o Dios), hace que el riesgo sea un problema ideal para las maniobras políticas” \[24\].

Es claro que las ciencias sociales y de la comunicación todavía tienen mucho que indagar y validar sobre los temas de la percepción del riesgo y la comunicación del riesgo. Sin embargo, es clarísimo que, si los enfoques provenientes de éstas se consideraran juntos, en lugar de abordarse desde perspectivas aisladas, deberían proporcionar una amplia gama de conocimientos teóricos y de resultados empíricos que podrían ayudar a los investigadores del riesgo a comprender mejor las percepciones, valoraciones y respuestas individuales y colectivas a las situaciones de riesgo y, con base en ellas, diseñar las mejores alternativas para reducir sus vulnerabilidades. A los tomadores de decisiones ayudaría a implementar medidas con mayor probabilidad de aceptación y de más alta eficacia social y política; y a los comunicadores del riesgo, entender en mejor medida, demandas y preocupaciones del público, así como las claves para construir los mensajes más acertados.

En esa medida, la comunicación del riesgo debe asumirse como un pilar en la construcción de una gobernanza del riesgo, en la que los principios de transparencia y rendición de cuentas trascienda la política pública y se incorporen en exigencias a empresas multinacionales y agentes generadores de riesgo, y en la que los canales de comunicación sean su medio de difusión y control social. Por tanto, la comunicación del riesgo para la gobernanza debe permitir, a través de su actuación, reducir los niveles de incertidumbre, propiciar un aumento de la participación en la toma de decisiones, potenciar procesos eficientes y racionales de autorregulación y ser agente de procesos democráticos. Como se ve, no se trata simplemente de informar sobre alarmas tempranas, procesos de reubicación o restricciones de ocupación y uso del suelo.

Sin embargo, el objetivo de la comunicación del riesgo no debe ser inducir a la gente a aceptar lo que el comunicador cree que es mejor para ellos. El programa de comunicación ideal debe propiciar la formación de sujetos activos capaces de valorar la información disponible, para formar juicios bien equilibrados, de acuerdo con la evidencia de los hechos, el peso de los diversos argumentos y sus propias necesidades, intereses y expectativas. El objetivo final de la comunicación de riesgos es reconciliar la experiencia, los intereses y las preferencias públicas, con las realidades políticas e institucionales de la sociedad, para así coadyuvar en la construcción de comunidades más informadas y conscientes de las situaciones territoriales más equitativas y seguras.

