---
title: "METODOLOGÍA"
number-sections: false
---


La investigación fue de corte cualitativo en tanto permitía profundizar en elementos determinados de la realidad social desde dinámicas particulares del contexto \[56\]. Siguió los principios del enfoque hermenéutico centrado en el estado de la cuestión, entendiéndose como

\[…\] la producción científica reciente en torno a la vivencia que se desea investigar. La cuestión, en una investigación cualitativa con enfoque hermenéutico, es una cosa que se pretende crear, y su existencia será posible si porta algo novedoso. Por eso se requiere ir al horizonte del pasado para indagarlo \[57\].

Aquellas vivencias, esto es, los efectos particulares de lo vivido que provocan significados perdurables \[58\] estuvieron direccionadas desde los componentes sociales en el proceso de reasentamiento poblacional. Así se realizó análisis de contenido categorial a doscientos documentos (libros, artículos, ensayos, trabajos de grado, tesis post-graduales) realizados en países latinoamericanos en el periodo 1991–2015, cuyo análisis fue el reasentamiento poblacional asociado a amenaza natural, seis grupos focales (tres con comunidades reasentadas y tres con expertos nacionales en materia de reasentamiento) y siete entrevistas semiestructuradas (seis a representantes del Sistema Nacional de Gestión del Riesgo de Desastres y a un experto en reasentamiento).

Los instrumentos empleados fueron: (1) matriz de análisis por medio de la cual se develaron tendencias y rupturas entre posibles unidades de significación, que llevaron a la conformación de categorías emergentes y, en consecuencia, a la organización de los hallazgos, (2) Fichas técnicas que en palabras de Hochman y Montero \[59\] constituyen “la memoria fiel del investigador…el depósito donde se acumulan los datos que obtiene en su trabajo” en consecuencia, es el instrumento donde se consignaron los principales elementos de los documentos revisados, con el fin de tener “una constante fuente de información, creciente y flexible” \[59\].

