---
title: "GESTIÓN DEL RIESGO EN CALI Y SU RELACIÓN CON LA OCURRENCIA DE EVENTOS HISTÓRICOS"
number-sections: false
---


El municipio de Santiago de Cali, específicamente su área urbana, fue un epicentro importante de recepción de flujos migratorios, convirtiéndose en un centro de actividades económicas para una vasta porción del eje comercial y en un polo de desarrollo para la región \[66\]. Sin embargo, al mismo tiempo fue consolidando un desarrollo desordenado de su trama urbana.

En este contexto, debido a la carencia de instrumentos institucionales para una adecuada planificación de la ciudad, se conformaron asentamientos ilegales que derivaron posteriormente en conflictos por la tierra \[67\] y en la toma de acciones populares por parte de la población migrante para acceder a un predio y a la aplicación de políticas de desarrollo urbano, propiciando la dilatación físico-urbana y la ampliación del perímetro urbano entre 1950 y 1990 hacia el oriente de la ciudad \[68\]. Se consolido un modelo de ciudad que muestra una expansión discontinua, dispersa e incontrolada, mediante la ocupación de terrenos aislados y sin urbanizar.

Cuando se analiza la distribución espacial de los eventos históricos ocurridos en el municipio, específicamente para el caso de inundaciones y movimientos en masa, se logra evidenciar que existe una mayor concentración hacia las zonas y barrios que recibieron la mayor parte de la población inmigrante y que se consolidaron de manera ilegal. Situación que, demuestra como los problemas en planificación se ven materializados en la ocurrencia fenómenos que pueden dejar un impacto sobre el territorio urbano.

A nivel reglamentario, el municipio cuenta con diferentes instrumentos para la gestión del riesgo que se han desarrollado a través de los años. El primero de estos, corresponde al Plan General para la Atención de Emergencias en Cali, realizado en el año 1989 por el Fondo de Emergencia Ciudadana (FES) y el Comité Operativo de Emergencia (COE) \[69\]. Este instrumento, tuvo como objetivo principal, plantear estrategias previas a la ocurrencia de los eventos, durante el periodo de emergencia y medidas de reparación de daños.

En el 1996, se formuló el Plan de Mitigación de Riesgos para Cali, el cual generó acciones de mitigación, intervenciones físicas y de planeación territorial, constituyéndose en una base aprovechable para el diseño y puesta en funcionamiento a futuro de un Plan de Gestión de Riesgos \[70\].

Posteriormente, en el año 2009 mediante el acuerdo Decreto 411.020.0744 se adopta el Plan Local de Emergencias y Contingencias del municipio de Santiago de Cali (PLEC) \[70\]. Prioriza los escenarios de riesgo, de sismos e inundaciones como los que podrían generar más daños y mayores damnificados en el municipio.

Todos estos instrumentos anteriormente mencionados, se enmarcaron en un enfoque de la atención del desastre, de acuerdo a la normatividad vigente a la fecha de su formulación. Con la entrada en vigencia de la Ley 1523 de 2012 \[71\] y del Decreto 1807 de 2014 \[72\], se cambia el paradigma de la gestión del riesgo en el país y se resalta la importancia de incorporarla en los procesos de planificación del territorio.

En sentido, surge la obligatoriedad para todas las entidades de formular planes de gestión del riesgo. El municipio de Santiago de Cali, en cumplimiento con la normatividad establecida, adopta en el año 2012 su Plan Municipal de Gestión del Riesgo de Desastres, mediante Decreto 411.020.0681 \[73\]. Sin embargo, este proceso solamente se realizó en el papel, dado que no llegó a la caracterización de escenarios de riesgos y a la formulación de un componente programático.

Por otro lado, en el año 2014 en la Revisión y Ajuste del de Plan de Ordenamiento Territorial del municipio, se involucra la gestión del riesgo en todos los componentes del plan, teniendo en cuenta estudios existentes, el planteamiento de acciones y medidas \[4\].

Con base a todo lo anterior, se debe mencionar que, de acuerdo al estudio de historicidad realizado en el presente trabajo, estos instrumentos para la gestión del riesgo no han representado una herramienta contundente que permitan dar frente a la ocurrencia de fenómenos en el municipio, sobretodo de inundación y movimiento en masa, pues en los últimos años se muestra un aumento significativo en la frecuencia de ocurrencia de estos eventos.

Finalmente, dado que este trabajo hace parte de la formulación del Plan Municipal de Gestión del Riesgo de Santiago de Cali, desarrollado en el año 2018, resulta conveniente analizar en un futuro, su impacto en la frecuencia de ocurrencia y severidad de eventos.

