---
title: "RECOMENDACIONES GENERALES"
number-sections: false
---


Es importante destacar que el cuidado de los animales y el cuidado de las personas exige preparación técnica, planificación y una importante capacidad de coordinación entre quienes participan en ella. El mejoramiento del bienestar animal en situaciones de emergencias y desastres no siempre progresa a lo esperado, la mayor parte del tiempo son los humanos quienes causan la mayoría de los problemas de bienestar animal. Por lo tanto, es necesario garantizar que se tenga en cuenta los aspectos del bienestar humano para lograr mejoras efectivas en el bienestar animal \[30\].

Para facilitar la atención a las personas y a los animales, las autoridades de manejo de emergencias y la comunidad, debe realizar alianzas en esta etapa de planificación. Una vez hecho esto, es más probable que los asuntos importantes puedan atenderse durante el desastre. Además, los recursos o personas más calificadas o con más experiencia pueden hacerles frente a los asuntos pertinentes y hablar con el público. Hay funciones en asuntos públicos adicionales que pueden ser utilizados para construir un programa fuerte ante emergencias. Aquí están algunas sugerencias:

  - > Concientizar a los grupos comunitarios

  - > Brindar formación a grupos humanitarios locales, tiendas de animales, asociaciones y federaciones. Se deben asignar roles y funciones a diferentes entidades de manejo de emergencias, veterinarios, trabajadores de alberges y educadores para lograr un trabajo conjunto.

  - > Desarrollar relaciones personales con los medios de comunicaciones locales y no solo a través de llamadas o correos electrónicos para los comunicados públicos.

  - > Ofrecer presentaciones en las escuelas locales primarias y secundarias sobre cómo mejorar el cuidado de los animales en situaciones de emergencias y desastres.

  - > Invitar a los medios de comunicaciones a participar cuando se realicen ejercicios de simulación o simulacros, ya sea como participante o como evaluador.

En el entrenamiento de preparación para desastres, se debe suponer que el personal de manejo de emergencias está familiarizado con sus derechos y responsabilidades, y que los proveedores de cuidado animal son competentes para tratar los asuntos relacionados con animales. Ningún agente infeccioso, podría explicar las diferencias existentes entre humanos y animales, sin embargo, los gobiernos, las instituciones académicas, los profesionales de la salud y las entidades que se deberían ocupar de ello, se han mantenido separados entre ramas de la misma ciencia médica, separando entre médicos humanos y médicos veterinarios saberes, experiencias y soluciones.

