---
title: "Capítulo 13. Gestión del riesgo por inundaciones: un metamodelo para el desarrollo de artefactos participativos. Caso de estudio en la ecorregión de La Mojana (Colombia)"
subtitle: "Investigaciones en gestión del riesgo de desastres para Colombia"
author: "UNGRD"
date: "2021"
title-block-banner: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=2072"
number-sections: false
---


Al analizar los instrumentos de planeación para la gestión del riesgo por inundación, se lográ identificar la falta de armonización entre estos. Específicamente a nivel de escalas espaciales y temporales. Lo que genera un reto para el desarrollo de modelos integrados. Se observa en la modelación participativa un gran potencial para su armonización, donde más que la integración de los modelos, se logre la integración de las ideas por parte de los actores participantes en los ejercicios de modelación.

+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **TRABAJO FUTURO**                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| 1.  A futuro, resulta interesante realizar ejercicios de modelado participativo con actores vinculados a Entidades Nacionales y analizar cómo la imagen que tienen del territorio interactúa con la imagen que tienen las comunidades que allí habitan. El hecho de tener diferentes enfoques sobre "desarrollo" o "buen vivir" genera aún mayores retos en términos de valores, convivencia y generación de acuerdos.                                                                                                                                                                                                    |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| 2.  La integración de los tres modelos también es un reto y puede ser viable como trabajo futuro. Por ejemplo, se podrían procesar imágenes y videos de MOJANAREAL para extraer patrones, reglas y atributos que se pudieran integrar en MOJANA y MOJANACOOP. Esto evidencia que la integración puede ser viable no solo al interior de cada artefacto, sino también entre los artefactos.                                                                                                                                                                                                                                |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| 3.  Uno de los principales retos a futuro, es trabajar en la incorporación de la vulnerabilidad social en la evaluación de riesgo por inundación. Abordándola de manera integrada con la amenaza y los demás componentes de la vulnerabilidad. En este trabajo se demostró que las condiciones de vulnerabilidad social pueden aumentar o disminuir el riesgo por inundación. Actualmente, si esto no se tienen en cuenta, muchas de las intervenciones podrían estar sobreestimándose o subestimándose. Lo que afecta directamente los procesos de gestión presupuestal del riesgo y la calidad de vida de la población. |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

**AGRADECIMIENTOS**

Se agradece a las comunidades de la Mojana que hicieron parte de este proyecto en San Marcos (Sucre), Nechí (Antioquia), Mompox (Bolívar), Magangué (Bolívar), Montelíbano (Córdoba). A Colciencias, entidad que otorgó la beca doctoral para el desarrollo de esta investigación, en el marco de la Convocatoria 567 de 2012. A la Unidad Nacional para la Gestión del Riesgo de Desastres, donde a través del proyecto "Evaluación probabilista del riesgo por inundación lenta en las cabeceras municipales de San Marcos (Sucre), Montelíbano (Córdoba), Mompox (Bolívar) y Magangué (Bolívar)", se pudo complementar el trabajo de campo. A la Pontificia Universidad Javeriana, donde se desarrolló la tesis doctoral.

**IDENTIFICACIÓN DE AUTORES**

Paula Andrea Villegas González [CvLAC](https://scienti.minciencias.gov.co/cvlac/visualizador/generarCurriculoCv.do?cod_rh=0000438405)

Nelson Obregón Neira [CvLAC](http://scienti.colciencias.gov.co:8081/cvlac/visualizador/generarCurriculoCv.do?cod_rh=0000194077)

**BIBLIOGRAFÍA**

1.  Congreso de Colombia. (2012). Ley 1523 de 2012. 58 p.

2.  Ministerio de Vivienda Ciudad y Territorio (2014). Decreto 1807 de 2014. Bogotá. D.C. 19 p.

3.  Medina-Sanson, L., Guevara-Hernández. F. & Tejeda-Cruz C. (2014). Urbis: Revisión crítica y propuesta para integrar los conceptos de tierra, paisaje y territorio. *Boletín Científico Sapiens Research*, 4(1), 54--60.

4.  Schneider, S. & Peyré Tartaruga, I. (2006). Territorio y enfoque territorial: de las referencias cognitivas a los aportes aplicados al análisis de los procesos. *Desarro Rural Organizaciones, Instituciones y Territorio*, 71--102.

5.  Halliday, A., & Glaser M. A. (2011). Management Perspective on Social Ecological Systems: A generic system model and its application to a case study from Peru. *Human Ecology Review*, 18(1), 1--18.

6.  Vanhulst, J., & Beling, A. E. (2013). El Buen vivir: una utopía latinoamericana en el campo discursivo global de la sustentabilidad. *Polis*, 36.

7.  Remolina, G. (2014). *Del BIG BANG de las ciencias a su integración en el pensamiento complejo*. 17 p.

8.  DNP (Departamento Nacional de Planeación), FAO (Organización de las Naciones Unidas para la Agricultura y la Alimentación). (2003). *Programa de desarrollo sostenible de la región de la Mojana, Colombia*. Primera edición. Comunicaciones IG, editor. Bogotá. 48 p.

9.  DNP (Departamento Nacional de Planeación). (2012). *Plan integral de ordenamiento ambiental y desarrollo territorial de la región de la Mojana: caracterización territorial*. 91 p.

10. Aguilera, M. (2004) *La Mojana: riqueza natural y potencial económico*. Documentos de trabajo sobre economía regional.

11. Villegas-González, P. A., Triviño-León, N., Escobar-Vargas, J. A., Obregón-Neira, N., González-Méndez, M., González-Salazar, R. E., et al. (2016). Modelación Integrada de Sistemas socio-ecologicos Complejos: Caso de Estudio la Ecorregión de la Mojana. *Revista de Ingenieria Universidad Distrital*, 391--410.

12. Kroes, P. (2012). Engineering design. En P. Kroes (Ed.), *Technical Artefacts: Creations of Mind and Matter: A Philosophy of Engineering Design* (pp. 127-161). Dordrecht: Springer Netherlands.

13. Arendt H. (2009). *La condición humana*. Editorial Paidos. Buenos aires.

14. Epstein, J. (2008). Why model? *Journal of Artificial Societies and Social Simulation*, 11(4), 12.

15. Voinov, A., & Bousquet, F. (2010). Modelling with stakeholders. *Environmental Modelling & Software*, 25(11), 1268-1281. https://doi.org/10.1016/j.envsoft.2010.03.007

16. Abel, N., Ross, H., Herbert, A., Manning, M., Walker, P. & Wheeler, H. (1998). *Mental models and communication in agriculture*. 90 p.

17. Molero Melgarejo, E. (2018) *La modelización hidrológica-hidráulica y los sistemas de información geográfica* (pp 1--5).

18. Escobar-Vargas, J. A. (2015). *Notas de clase Mecánica de Fluidos Computacional*.

19. Wirasaet, D., Kubatko, E. J., Michoski, C. E., Tanaka, S., Westerink, J. J. & Dawson, C. (2014) Discontinuous Galerkin methods with nodal and hybrid modal/nodal triangular, quadrilateral, and polygonal elements for nonlinear shallow water flow. *Computer Methods in Applied Mechanics and Engineering*, 270(1), 113--49. <https://doi.org/10.1016/j.cma.2013.11.006>

20. Filatova, T., Verburg, P. H., Parker, D. C., & Stannard, C. A. (2013). Spatial agent-based models for socio-ecological systems: Challenges and prospects. *Environmental Modelling & Software*, 45, 1-7. <https://doi.org/10.1016/j.envsoft.2013.03.017>

21. González-Pérez C, Henderson-Sellers B. (2008). *Metamodelling for Software Engineering*. John Wiley & Sons. 219 p.

22. UNGRD (Unidad Nacional para la Gestión del Riesgo de Desastres). (2018). *Evaluación probabilista del riesgo por inundación lenta en las cabeceras municipales de San Marcos (Sucre), Montelíbano (Córdoba), Mompox (Bolívar) y Magangué (Bolívar)*. Bogotá, D.C.

23. Villegas González, P. A. (2018). *Gestión del riesgo por inundaciones: un metamodelo para el desarrollo de artefactos participativos Modelos integrados de sistemas socio-ecológicos: caso de estudio en la ecorregión de la Mojana*. Pontificia Universidad Javeriana.

24. Villegas-González, P. A., Ramos-Cañón. A. M., González-Méndez, M., González-Salazar, R. E., Durán Gaviria, E. D., De Plaza Solórzano, J. S., et al. (2017). *Gestión del riesgo en Colombia: vulnerabilidad, reducción y manejo de desastres*. Bogotá, D. C. 111 p.

25. UNGRD (Unidad Nacional para la Gestión del Riesgo de Desastres). (2018). *Evaluación probabilística del riesgo por inundación lenta en municipios priorizados*. Bogotá.

26. Wooldridge, M., Jennings, N. R., & Kinny, D. (2000). The Gaia Methodology for Agent-Oriented Analysis and Design. *Autonomous Agents and Multi-Agent Systems*, 3(3), 285-312. <https://doi.org/10.1023/A:1010071910869>

27. Villegas, P. A., Melgarejo, M. & Pérez, E. (2014). *MOJANA: Modelo Organizacional Jerárquico de Agentes Naturales del Agua*. Pontificia Universidad Javeriana

28. Pulido, H. A. (2015). *Modelo de interacción social para agentes artificiales en la arquitectura Mojana* (Tesis de grado). Universidad Distrital Francisco José de Caldas. Bogotá, D.C.

29. DNP (Departamento Nacional de Planeación). (2010). *Orientaciones conceptuales y metodológicas para la formulación de visiones de desarrollo territorial*. Dirección de Desarrollo Territorial Sostenible, Subdirección de Ordenamiento y Desarrollo Territorial. Bogotá, D.C.

30. Berger, T., Birner, R., McCarthy, N., DíAz, J., & Wittmer, H. (2007). Capturing the complexity of water uses and water users within a multi-agent framework. *Water Resources Management*, 21(1), 129-148. <https://doi.org/10.1007/s11269-006-9045-z>

**Lista de pares revisores**

**Roberto Ariel Abeldaño** \| Universidad de la Sierra Sur y CONACYT, México

**Ana Beatriz Acevedo Jaramillo** \| Departamento de Ingeniería Civil, Universidad EAFIT, Medellín, Colombia

**Melissa Acosta \|** Universidad de la Costa, Barranquilla, Colombia

**Franck A. Audemard M.** \|Escuela de Geología, Minas y Geofísica, Universidad Central de Venezuela

**Edier Aristizábal** \| Departamento de Geociencias y Medio Ambiente, Universidad Nacional de Colombia, Sede Medellín

**Álvaro Ávila-Díaz** \| Department of Agricultural Engineering, Universidade Federal de Viçosa, Brasil

**José Emilio Baró Suárez** \| Facultad de Geografía, Universidad Autónoma del Estado de México, México

**Gustavo Barrantes** \| Escuela de Ciencias Geográficas, Universidad Nacional, Costa Rica

**Huáscar Bolívar Vallejo** \| Universidad Mayor de San Simón, Bolivia

**Mireille Escudero** \| Instituto de Ingeniería, Universidad Nacional de México, Ciudad de México, México

**María Adelaida Farah** \| Facultad de Estudios Ambientales y Rurales, Pontificia Universidad Javeriana, Colombia

**Silvia E. Fontana** \| Universidad Católica de Córdoba, Argentina

**Jorge Pedro Galve** \| Departamento de Geodinámica, Universidad de Granada, España

**Helbert García-Delgado** \| Servicio Geológico Colombiano, Grupo de evaluación de amenazas por movimientos en masa, Colombia

**Victor Manuel García Lemus** \| Presidente de la Red Universitaria de las Américas y el Cribe para la RRD

**Miguel Ángel Imaz** \| Universidad Autónoma de Baja California Sur, México

**Miguel Ángel Jaimes Téllez** \| Instituto de Ingeniería, UNAM, México

**Santiago Henao Villegas** \|Facultad de Medicina Veterinaria y Zootecnia, Escuela de Graduados, Universidad CES, Medellín, Colombia

**David Ortega-Gaucin** \| Instituto Mexicano de Tecnología del Agua, México

**Juan Diego Jaramillo Fernández** \| Departamento de Ingeniería Civil, Universidad EAFIT, Medellín, Colombia

**Andrés León Prieto** \| Universidad del Bosque - Escuela Colombiana de Medicina, Colombia

**Ana Lucía Maldonado** \| Instituto de Investigaciones en Educación, Universidad Veracruzana, Xalapa, México

**Roberto J. Marín** \| Facultad de Ingeniería, Universidad de Antioquia, Medellín, Colombia

**Hazel Marsh** \| University of East Anglia, Reino Unido

**Mónica Elizabeth Mejía Escalante** \| Escuela del Hábitat, Facultad de Arquitectura, Universidad Nacional de Colombia, Sede Medellín

**Ricardo J. Molares B.** \| Perito oceanógrafo -- DIMAR -- CP3, Colombia

**Erick Cajigal Molina** \| Universidad Autónoma del Carmen, México

**Claudia Montero-Liberona** \| Facultad de Comunicaciones, Pontificia Universidad Católica de Chile, Chile

**Nelson Obregón** \| Instituto Javeriano del Agua, Pontificia Universidad Javeriana, Colombia

**Juan Andrés Oviedo Amézquita** \| FC Control y Diseño de Estructuras SAS, Colombia

**Aceneth Perafán Cabrera** \| Departamento de Historia, Universidad del Valle, Colombia

**Rogelio Pineda Murillo** \| Consultor, Planificación Territorial, Desarrollo Sostenible y Medio Ambiente, Geografía y Cambio Climático, Colombia

**Carlos E. Reinoza** \| CICESE - Centro de Investigación Científica y de Educación Superior de Ensenada, Baja California, México

**Eduardo Reinoso** \|Instituto de Ingeniería, UNAM, México

**Miguel Enrique Sarmiento** \| Dirección de Gestión del Ordenamiento Ambiental y Territorial, CAR de Cundinamarca, Colombia

**Juan Sebastián de Plaza Solórzano** \| Universidad Católica de Colombia

**Olga Patricia Quintero García** \| Corpocaldas, Manizales, Colombia

**Vladimir G. Toro** \| Facultad de Ingeniería, Universidad de Antioquia, Medellín, Colombia

**Mauricio A. Torres Méndez** \| Universidad de Concepción, Chile

**Diego Soler Tovar** \| Universidad de la Salle, Bogotá, Colombia

**Hernando Uribe Castro** \| Universidad Autónoma de Occidente, Cali, Colombia

**Jairo Andrés Valcárcel Torres** \| I+R Consultores en Ingeniería y Riesgos. S.A.S, Bogotá, D.C, Colombia

**Francisco A. Velandia** \| Escuela de Geología, Universidad Industrial de Santander, Bucaramanga, Colombia
