---
title: "Capítulo 14. Evaluación probabilista del riesgo por sequía en el sector agrícola de Colombia"
subtitle: "Investigaciones en gestión del riesgo de desastres para Colombia"
author: "UNGRD"
date: "2021"
title-block-banner: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=2072"
number-sections: false
---


AAbrasión de acantilados, 417Acompañamiento psicosocial, 201Actividades agropecuarias, 232Adaptación basada en ecosistemas, 434Adaptación basados en ecosistemas, 436*Adaptación socio-económica*, 272AIS-300, 4Alternativas de mitigación y control, 434Amenaza, 340, 378, 448, 474Amenaza probabilista, 51Amenaza sísmica, 4Amenaza y vulnerabilidad, 434Amenaza y vulnerabilidad por erosión costera, 436Análisis de riesgo, 342Animales, 230Animales en la sociedad, 232Artefactos, 500Aumento del nivel del mar, 416BBienestar animal, 234Bioseguridad para respuesta a animales, 240Bloque Norte de los Andes, 161, 167Buen vivir, 476CCambio climático, 106Clima extremo, 106Clima marítimo, 414COCONet, 167Coeficientes óptimos de diseño, 4Coeficientes sísmicos de diseño, 4Componentes psicosociales, 202, 205, 207, 221, 222Comportamiento animalComportamiento animal bajo condiciones de stress, 238Comportamiento animal en incidentes, 237Comunicación del riesgo, 279Comunición del riesgo, 284Comunición humana, 282Comunidades, 474Concentración de animales, 236Concreto reforzado, 58Cuencas, 340Cuidado de los animales y manejo de emergencias, 234Cultivo de maíz, 91DDegradación ambiental, 257Deslizamientos, 340Diseño, 479EEnfermedades zoonóticas, 233Equilibro ecosistémico, 203Erosión costera, 414, 416, 435Escenario de riesgo, 439Especies silvestres, 231Espectros de diseño, 4Espolones, 414, 415Estrategias comunicativas, 279Estructuras organizativas, 209Estudios históricos, 301, 302, 303, 304historicidad por sismos, 301objetivos directos, 305objetivos indirectos, 306planificación territorial, 306Evaluación de amenaza por movimientos en masa, 341Evaluación de riesgo por inundación., 503evaluación probabilista de la amenaza por sequía, 97Evaluación probabilista del riesgo, 92evaluación probabilista del riesgo por sequía, 95Evaluación prospectiva del riesgo, 91Eventos hidrometeorológicos, 92Experiencia educativa, 256Experiencias locales, 279Exposición agrícola, 111Exposición de edificaciones, 51FFactor de seguridad, 350Factores detonantes, 344Factores para manejar animales, 238Floculación, 417Frecuencia en el nivel de amenaza, 384Frente halino, 417GGenerador de clima estocástico, 92Geoamenazas, 434Geodesia de imágenes, 177Geodesia espacial GPS, 163Geodinámica, 161Geoformas, 406Geomática, 360GeoRED, 167Gestión del riesgo, 91Gestión integral del riesgo, 92GNSS, 161Gobernanza del riesgo, 287GPS De-ramping, 187HHistoricidad, 302, 304, 315, 321, 332IIber 2D, 378Infraestructura escolar, 45InSAR, 161, 177Integración de resultados GPS-InSAR, 189Integridad socio-ambiental, 201Intensidad en el nivel de amenaza, 384Interferograma diferencial, 178Intervención correctiva, 439Intervención prospectiva, 439Inundación, 324, 474Inundaciones, 302, 325, 327, 333, 377, 378MMampostería, 58Mampostería confinada, 62Mampostería no reforzada, 61Mampostería reforzada, 63Manejo de animales, 237Manejo de especies silvestres, 241Mantenimiento de la salud pública, 236Mapas de amenaza integrada por sequía, 91Marco de Referencia Terrestre, 168Marco de Sendai, 218Marco global de referencia, 164Medidas blandas y duras o mixtas, 436Medidas de Bioseguridad, 241Medios de vida, 232Metodología intensivista, 301Mitigación, 378, 439Mitigación del riesgo, 49Mitigación del riesgo sísmico, 45Modelación, 474Modelación hidráulica, 378Modelación integrada, 500Modelo de elevación digital (DEM), 393Modelo hidráulico 2D, 377Modelos basados en agentes, 481Modelos de bloques cinemáticos, 164Modelos probabilistas, 91Modos de habitar, 217Modos de vida, 203, 204, 221Monitoreo, 439Movimientos en masa, 301, 302, 319, 321, 322, 340, 341, 380Movimientos en masa e inundaciones, 301NNivel del mar, 414Norma Colombiana de Construcción Sismo Resistente, 4NSR 10, 4OObras costeras, 416Oleaje, 417One Health, 231Optimización de costos totales, 4PPaisaje, 435Participación ciudadana, 204Participación comunitaria, 267*Participación y organización social*, 207, 209, 214Percepción de la comunidad, 395Percepción del riesgo, 286Pérdida anual esperada, 91Pérdidas probables, 349Performativo, 221Periodo de retorno, 4, 377Planes de mitigación del riesgo, 56Planificación costera, 435Políticas de los albergues, 246Polo de Euler, 169, 175Pórticos de concreto reforzado, 58Pórticos de concreto reforzado con muros de mamposteria, 59Pórticos de concreto reforzado con muros de mampostería generando columna corta, 60Preocupaciones medioambientales., 248Priorización de edificaciones, 57Protección costera, 414Proyección social, 265Psicosocial, 203RRadar de Apertura Sintética, 187Radar Interferométrico de Apertura Sintética, 187Reasentamiento social, 201, 204Reducción del riesgo de desastres, 201Reforzamiento estructural, 45, 55Registro e identificación de animales, 239Responsabilidad social, 255, 256Responsabilidad social universitaria, 265Respuesta de las personas a los animales en desastres, 233Riesgo, 349, 359, 474Riesgo por sequía, 91Riesgo por sequía para el cultivo de maíz, 120Riesgo sísmico, 50RINEX, 168Risk Targeted Ground Motion, 4SSalud física y mental, 220Salud mental, 247Salud pública, 234Salud pública y epidemiologia de los animales en desastres, 247Sector agropecuario, 91, 92Sector escolar, 46Seguridad alimentaria, 231Sequía, 91Sequía en Colombia, 108Series climáticas, 101Servicio Geológico Colombiano, 167Sismos, 301, 302, 314, 315, 316, 317, 332Sistema Terrestre de Referencia, 168Sistemas de Información Geográfica, 360Sistemas socio-ecológicos, 475, 476Sostenibilidad, 201, 221Subsidencia, 161, 177TTajamares, 414, 417Taller comunitario, 279Tectónica de placas, 161Tejido social, 255Teoría de la comunicación, 279Territorio, 435, 475Territorio afectado, 384Tipologías de concreto reforzado, 58Tipologías de construcción escolar, 57Tipologías de mampostería, 61Trabajo colaborativo, 256UUna salud, 230Vvectores de velocidad geodésica, 171Vientos alisios, 415Vulnerabilidad, 91, 340, 349, 359, 448, 474Vulnerabilidad de cultivos, 92Vulnerabilidad de los animales en la agricultura, 245*Vulnerabilidad hídrica*, 272Vulnerabilidad sísmica, 54Vulnerabilidad social, 503Vulnerabilidad socioeconómica y ambiental, 257ZZona de Convergencia Intertropical, 264Zonas de deformación en límites de placas, 164Zoonosis, 237Zootecnia, 232

[^1]: No se consideran sistemas de protección sísmica en la estimación de los costos futuros.

[^2]: La drástica reducción de las aceleraciones de diseño en Bucaramanga se debe, aparentemente, a errores de modelación en versiones anteriores del código NSR. Los nuevos modelos de amenaza sísmica han revelado que las aceleraciones esperadas en la ciudad no son tan altas como se creía.
